import { PersistentCollection } from '../storage/persistent';
import { Storage } from '../storage/idb';
import { readJsonState, writeJsonState } from '../storage/json-state';
import { loadProjects } from '../projects/state';
import { loadDocuments } from '../documents/state';

const prefix = 'example-space-';
const day = 86_400_000;
const id = (name: string) => `${prefix}${name}`;
const meta = (name: string, now: number) => ({ id: id(name), created_at: now, updated_at: now, deleted_at: null, synced_at: null });

export async function generateExampleData(now = Date.now()): Promise<void> {
  const projects = [{ ...meta('roofing', now), name: 'Northwest Roofing', color: '#315a85' }, { ...meta('studio', now + 1), name: 'Side Door Studio', color: '#8a5bd6' }];
  const stores = ['projects', 'events', 'tasks', 'launchpad_links', 'time_logs'] as const;
  const records: Record<string, Record<string, unknown>[]> = {
    projects,
    events: [{ ...meta('event-site-measure', now + 2), project_id: id('roofing'), title: 'Site measure — Henderson residence', description: 'Measure roof planes, photograph flashing, and confirm shingle color with the homeowner.', location: 'Henderson residence', starts_at: now + day, ends_at: now + day + 90 * 60_000, all_day: false, repeat: 'none', completed: false, source_type: 'manual', read_only: false }, { ...meta('event-client-call', now + 3), project_id: id('studio'), title: 'Discovery call — Harbor & Pine', description: 'Review their service pages, intake form, and launch goals.', location: 'Phone', starts_at: now + 2 * day + 16 * 60 * 60_000, ends_at: now + 2 * day + 17 * 60 * 60_000, all_day: false, repeat: 'none', completed: false, source_type: 'manual', read_only: false }],
    tasks: [{ ...meta('task-followup', now + 4), project_id: id('roofing'), title: 'Follow up on Cedar Street estimate', completed: false, priority: 'high' }, { ...meta('task-assets', now + 5), project_id: id('studio'), title: 'Export Harbor & Pine logo assets', completed: false, priority: 'normal' }, { ...meta('task-invoice', now + 6), project_id: id('roofing'), title: 'Send final invoice — Morrison roof', completed: true, priority: 'normal' }],
    notes: [{ ...meta('note-daily', now + 7), project_id: id('roofing'), title: 'Morning dispatch notes', content: JSON.stringify({ body: 'Call Cedar Street before the first site visit. Bring the moisture meter and two shingle samples.', checklist: [], pinned: true, archived: false, blurred: false }) }, { ...meta('note-ideas', now + 8), project_id: id('studio'), title: 'Web design ideas', content: JSON.stringify({ body: 'Try a before/after case-study layout for contractor sites: problem, process, proof, next step.', checklist: [], pinned: false, archived: false, blurred: false }) }],
    documents: [{ ...meta('doc-sales-playbook', now + 9), project_id: id('roofing'), title: 'Roofing sales playbook', content: '# Roofing sales playbook\n\n## Before the appointment\n- Review satellite imagery and prior estimates.\n- Bring samples and the right ladder notes.\n\n## During the visit\nDocument the roof condition clearly, explain options in plain language, and leave the homeowner with a next step.\n\n## Follow-up\nSend photos, scope, warranty details, and a simple decision date.' }],
    launchpad_links: [{ ...meta('link-crm', now + 10), project_id: id('roofing'), title: 'Roofing CRM', url: 'https://app.hubspot.com/', tags: ['sales', 'daily'], description: 'Lead follow-up and estimate pipeline.', pinned: true, archived: false, position: 0 }, { ...meta('link-inspiration', now + 11), project_id: id('studio'), title: 'Awwwards inspiration', url: 'https://www.awwwards.com/', tags: ['design', 'inspiration'], description: 'Reference for layout and interaction ideas.', pinned: true, archived: false, position: 0 }],
    time_logs: [{ ...meta('log-estimate', now + 12), project_id: id('roofing'), group_id: id('task-followup'), title: 'Follow up on Cedar Street estimate', description: 'Reviewed scope and prepared questions.', started_at: now - 75 * 60_000, ended_at: now - 30 * 60_000, duration_seconds: 45 * 60, active: false, paused: false, blurred: false }, { ...meta('log-homepage', now + 13), project_id: id('studio'), group_id: id('log-homepage'), title: 'Harbor & Pine homepage', description: 'Wireframed the service-page hero and proof section.', started_at: now - 3 * 60 * 60_000, ended_at: now - 2 * 60 * 60_000, duration_seconds: 60 * 60, active: false, paused: false, blurred: false }],
  };
  const add = (store: string, record: Record<string, unknown>) => records[store].push(record);
  for (let index = 1; index <= 12; index += 1) add('events', { ...meta(`roof-event-${index}`, now + 20 + index), project_id: id('roofing'), title: `${['Roof inspection', 'Material delivery', 'Homeowner follow-up', 'Crew check-in'][index % 4]} — Cedar Street ${index}`, description: 'Example roofing administration appointment.', location: 'Northwest service area', starts_at: now + (index + 1) * day + 9 * 60 * 60_000, ends_at: now + (index + 1) * day + 10 * 60 * 60_000, all_day: false, repeat: 'none', completed: false, source_type: 'manual', read_only: false });
  for (let index = 1; index <= 3; index += 1) add('events', { ...meta(`studio-event-${index}`, now + 40 + index), project_id: id('studio'), title: `${['Client review', 'Design sprint', 'Launch checklist'][index - 1]} — Studio client ${index}`, description: 'Example web-design calendar item.', location: 'Home studio', starts_at: now + (index + 2) * day + 13 * 60 * 60_000, ends_at: now + (index + 2) * day + 14 * 60 * 60_000, all_day: false, repeat: 'none', completed: false, source_type: 'manual', read_only: false });
  for (let index = 1; index <= 12; index += 1) add('tasks', { ...meta(`roof-task-${index}`, now + 60 + index), project_id: id('roofing'), title: `${['Confirm measurements', 'Request supplier pricing', 'Update estimate', 'Send customer recap'][index % 4]} — job ${index}`, completed: index % 5 === 0, priority: index % 3 === 0 ? 'high' : 'normal' });
  for (let index = 1; index <= 3; index += 1) add('tasks', { ...meta(`studio-task-${index}`, now + 80 + index), project_id: id('studio'), title: `${['Polish case study', 'Compress image exports', 'QA mobile navigation'][index - 1]} — client ${index}`, completed: false, priority: 'normal' });
  for (let index = 1; index <= 10; index += 1) add('launchpad_links', { ...meta(`roof-link-${index}`, now + 100 + index), project_id: id('roofing'), title: `${['Supplier portal', 'Roof pitch calculator', 'Permit lookup', 'Insurance checklist', 'CRM pipeline'][index % 5]} ${index}`, url: `https://example.com/roofing/${index}`, tags: ['roofing', index % 2 ? 'sales' : 'operations'], description: 'Example roofing work link.', pinned: index <= 2, archived: false, position: index });
  for (let index = 1; index <= 20; index += 1) add('launchpad_links', { ...meta(`studio-link-${index}`, now + 120 + index), project_id: id('studio'), title: `${['Font library', 'Color tool', 'Hosting dashboard', 'Design reference', 'Analytics'][index % 5]} ${index}`, url: `https://example.com/studio/${index}`, tags: ['design', index % 2 ? 'client' : 'tools'], description: 'Example web-design work link.', pinned: index <= 3, archived: false, position: index });
  for (let index = 1; index <= 30; index += 1) add('time_logs', { ...meta(`roof-log-${index}`, now + 150 + index), project_id: id('roofing'), group_id: id(`roof-log-group-${Math.ceil(index / 2)}`), title: `Roofing admin block ${index}`, description: 'Example estimating, scheduling, or customer follow-up time.', started_at: now - (index + 1) * 3_600_000, ended_at: now - (index + 1) * 3_600_000 + 25 * 60_000, duration_seconds: 25 * 60, active: false, paused: false, blurred: false });
  for (let index = 1; index <= 30; index += 1) add('time_logs', { ...meta(`studio-log-${index}`, now + 190 + index), project_id: id('studio'), group_id: id(`studio-log-group-${Math.ceil(index / 2)}`), title: `Studio design block ${index}`, description: 'Example design, copy, or client communication time.', started_at: now - (index + 1) * 2_400_000, ended_at: now - (index + 1) * 2_400_000 + 35 * 60_000, duration_seconds: 35 * 60, active: false, paused: false, blurred: false });
  for (let index = 1; index <= 19; index += 1) records.documents.push({ ...meta(`roof-doc-${index}`, now + 220 + index), project_id: id('roofing'), title: `Roofing workspace note ${index}`, content: `# Roofing workspace note ${index}\n\nA practical note about customers, crews, materials, and follow-up.`, tags: ['roofing', index % 2 ? 'sales' : 'operations'], archived: false, blurred: false });
  for (let index = 1; index <= 19; index += 1) records.documents.push({ ...meta(`studio-doc-${index}`, now + 250 + index), project_id: id('studio'), title: `Studio workspace note ${index}`, content: `# Studio workspace note ${index}\n\nA working note about client websites, visual systems, and launch details.`, tags: ['design', index % 2 ? 'client' : 'ideas'], archived: false, blurred: false });
  const storage = new Storage();
  for (const store of stores) { const collection = new PersistentCollection(store, storage); for (const record of records[store]) { const existing = await storage.get(store, record.id as string); if (existing) await collection.update({ ...existing, ...record } as never); else await collection.create(record as never); } }
  const existingDocs = readJsonState<any[]>('dashboard.documents.v1', []);
  const examples = [...records.notes, ...records.documents].map((record) => ({ ...record, tags: record.id === id('doc-sales-playbook') ? ['sales', 'process'] : ['ideas'], archived: false, blurred: false }));
  writeJsonState('dashboard.documents.v1', [...existingDocs.filter((record) => !String(record.id).startsWith(prefix)), ...examples]);
  const existingTimeLogs = readJsonState<Record<string, unknown>[]>('dashboard.time-logs.v1', []);
  writeJsonState('dashboard.time-logs.v1', [...existingTimeLogs.filter((record) => !String(record.id).startsWith(prefix)), ...records.time_logs]);
  writeJsonState('dashboard.routines.v1', [{ id: id('routine-dispatch'), project_id: id('roofing'), title: 'Prepare tomorrow’s route', description: 'Review appointments, weather, and materials.', frequency: 'daily', interval: 1, weekdays: [], ordinals: [], blurred: false, archived: false, last_completed_at: null }, { id: id('routine-studio'), project_id: id('studio'), title: 'Studio cleanup', description: 'Capture loose design ideas and close open tabs.', frequency: 'weekly', interval: 1, weekdays: [0], ordinals: [], blurred: false, archived: false, last_completed_at: null }]);
  await loadProjects();
  await loadDocuments(false);
  if (typeof window !== 'undefined') window.dispatchEvent(new CustomEvent('deskclerk:time-logs-changed'));
}
