import { Storage } from '../storage/idb';
import type { StoreName } from '../storage/models';
import type { BackendConfig } from '../integrations/backend';
import { createBackendClient } from '../integrations/backend';
import { setSyncState } from '../ui/sync';

const pending: Array<{ store: string; record: Record<string, unknown> }> = [];
let flushing = false;
let syncing = false;
async function config(): Promise<BackendConfig | null> { const settings = await new Storage().list('settings'); const values = new Map(settings.map((s) => [s.key, s.value])); if (values.get('backend.enabled') !== true || typeof values.get('backend.base_url') !== 'string' || typeof values.get('backend.device_token') !== 'string' || !values.get('backend.device_token')) return null; return { enabled: true, baseUrl: values.get('backend.base_url') as string, deviceToken: values.get('backend.device_token') as string, deviceId: values.get('backend.device_id') as string }; }
function expandChange({ store, record }: { store: string; record: Record<string, unknown> }): Array<Record<string, unknown>> { if (store !== 'settings' || typeof record.key !== 'string' || !Array.isArray(record.value)) return [{ ...record, store }]; const target = record.key === 'dashboard.time-logs.v1' ? 'time_logs' : record.key === 'dashboard.documents.v1' ? 'documents' : null; if (!target) return [{ ...record, store }]; const fallbackTime = Number(record.updated_at ?? Date.now()); return (record.value as Array<Record<string, unknown>>).map((item) => ({ ...item, id: typeof item.id === 'string' && item.id ? item.id : crypto.randomUUID(), created_at: Number(item.created_at ?? fallbackTime), updated_at: Number(item.updated_at ?? fallbackTime), deleted_at: item.deleted_at === undefined ? null : item.deleted_at, synced_at: item.synced_at === undefined ? null : item.synced_at, store: target })); }
async function flush(): Promise<void> { if (flushing || !pending.length) return; const cfg = await config(); if (!cfg) { setSyncState('local'); return; } flushing = true; setSyncState('syncing'); const batch = pending.splice(0, 50); const expanded = batch.flatMap(expandChange); try { await createBackendClient(cfg).pushSync(expanded.map((record) => record as never)); setSyncState('synced'); } catch { pending.unshift(...batch); setSyncState('error'); } finally { flushing = false; } }
export async function syncAll(): Promise<'skipped' | 'synced' | 'failed'> { if (syncing) return 'skipped'; const cfg = await config(); if (!cfg) { setSyncState('local'); return 'skipped'; } syncing = true; setSyncState('syncing'); try { await flush(); const result = await createBackendClient(cfg).pullSync(null) as { data?: { records?: Array<Record<string, unknown>> } }; const storage = new Storage(); for (const remote of result.data?.records ?? []) { const store = remote.store as StoreName; if (!['projects','notes','tasks','documents','events','time_logs','launchpad_links','settings'].includes(store)) continue; const { store: _store, ...record } = remote; const local = await storage.get(store, String(record.id)); if (!local || Number(record.updated_at ?? 0) > Number(local.updated_at ?? 0)) { if (local) await storage.update(store, record as never); else await storage.create(store, record as never); } } setSyncState('synced'); return 'synced'; } catch { setSyncState('error'); return 'failed'; } finally { syncing = false; } }
export function startBackendSync(): () => void { const handler = (event: Event) => { const detail = (event as CustomEvent).detail as { store: string; record: Record<string, unknown> }; pending.push(detail); void flush(); }; const configChanged = () => { void flush(); void syncAll(); }; window.addEventListener('deskclerk:record-changed', handler); window.addEventListener('deskclerk:backend-config-changed', configChanged); window.addEventListener('online', configChanged); void syncAll(); return () => { window.removeEventListener('deskclerk:record-changed', handler); window.removeEventListener('deskclerk:backend-config-changed', configChanged); }; }
