import { beforeEach, describe, expect, it, vi } from 'vitest';
import { get } from 'svelte/store';
import { draftForCommand, parseClerkInput } from '../src/lib/clerk/commands';
import { appendClerkResponse, approveDraft, clerkDrafts, clerkMessages, clerkPanelMode, clerkSessions, clearClerkHistory, denyDraft, newClerkChat, selectClerkChat, renameClerkChat, archiveClerkChat, deleteClerkChat, submitClerkInput } from '../src/lib/clerk/state';
import { buildClerkContext, buildClerkConversation, clerkSystemPrompt } from '../src/lib/clerk/ollama';
import { PersistentCollection } from '../src/lib/storage/persistent';
import { readJsonState } from '../src/lib/storage/json-state';

describe('Clerk command processor', () => {
  it('recognizes workspace commands', () => { expect(parseClerkInput('/open calendar')).toEqual({ type: 'open_view', view: 'calendar' }); expect(parseClerkInput('/task Send the proposal')).toEqual({ type: 'create_task', title: 'Send the proposal' }); expect(parseClerkInput('/note Remember this')).toEqual({ type: 'create_note', content: 'Remember this' }); });
  it('preserves plain-language input as a message', () => { expect(parseClerkInput('What should I focus on?')).toEqual({ type: 'message', content: 'What should I focus on?' }); expect(() => parseClerkInput('   ')).toThrow(); });
  it('turns mutations into draft actions', () => { expect(draftForCommand(parseClerkInput('/task Review build'))).toEqual({ type: 'create_task', payload: { title: 'Review build' } }); });
  it('turns natural-language note requests into drafts', () => { expect(parseClerkInput('Please create a new note that tells me how to peel a mango')).toEqual({ type: 'create_note', content: 'how to peel a mango' }); });
  it('provides date, timezone, and project context for relative-date requests', () => { const context=buildClerkContext({now:'7/20/2026, 9:00 AM',timezone:'America/Los_Angeles',projects:[{id:'p1',name:'Personal'}],currentProjectId:'p1'}); expect(context).toContain('America/Los_Angeles'); expect(context).toContain('Personal [p1]'); expect(context).toContain('next Tuesday'); });
  it('includes user-created workspace records so Clerk can answer about existing work', () => { const context=buildClerkContext({now:'7/20/2026, 9:00 AM',timezone:'America/Los_Angeles',projects:[{id:'p1',name:'Personal'}],currentProjectId:'p1',records:{documents:[{id:'d1',title:'Law office quote',content:'Follow up with the law office about their website redesign.',project_id:'p1'}],events:[],tasks:[],routines:[],launchpad_links:[],time_logs:[]}}); expect(context).toContain('Law office quote'); expect(context).toContain('website redesign'); });
  it('preserves multi-turn Clerk conversation roles for the AI request', () => { expect(buildClerkConversation([{role:'user',content:'Today is July 21.'},{role:'clerk',content:'Next Tuesday is July 28.'},{role:'user',content:'Create that event.'}])).toEqual([{role:'user',content:'Today is July 21.'},{role:'assistant',content:'Next Tuesday is July 28.'},{role:'user',content:'Create that event.'}]); });
  it('teaches the model the supported link, document, and time-log draft types', () => { expect(clerkSystemPrompt).toContain('launchpad_link'); expect(clerkSystemPrompt).toContain('document'); expect(clerkSystemPrompt).toContain('time_log'); });
});

describe('Clerk state engine', () => {
  beforeEach(() => clearClerkHistory());
  it('records user input without inventing a Clerk response', () => { submitClerkInput('What is on my calendar?'); expect(get(clerkMessages)).toHaveLength(1); expect(get(clerkMessages)[0].role).toBe('user'); });
  it('turns an AI JSON envelope into a pending draft', () => { submitClerkInput('Create a note'); appendClerkResponse('Here is the proposal.```json\n{"action":"create","object_type":"note","payload":{"id":"model-id","title":"Mango","content":"Peel a mango"},"summary":"Save a reusable mango peeling note."}\n```'); expect(get(clerkDrafts)[0].action.payload.id).toBe('model-id'); expect(get(clerkMessages).at(-1)?.content).toBe('Here is the proposal.'); });
  it('persists a pending draft and allows denial without executing it', () => { submitClerkInput('Create a note'); appendClerkResponse('{"action":"create","object_type":"note","payload":{"title":"Mango"},"summary":"Create the note."}'); const id=get(clerkDrafts)[0].id; expect(get(clerkDrafts)[0].status).toBe('pending'); denyDraft(id); expect(get(clerkDrafts)[0].status).toBe('denied'); });
  it('executes a task only after explicit approval', async () => { submitClerkInput('Create a task'); appendClerkResponse('{"action":"create","object_type":"task","payload":{"id":"model-id","title":"Review build"},"summary":"Create a review task."}'); const id=get(clerkDrafts)[0].id; expect(get(clerkDrafts)[0].status).toBe('pending'); await approveDraft(id); expect(get(clerkDrafts)[0].status).toBe('approved'); });
  it('creates an event in the calendar only after event draft approval', async () => { submitClerkInput('Book the quote'); appendClerkResponse('{"action":"create","object_type":"event","payload":{"title":"Quote booking for Dan","location":"8814 Straton Pl","starts_at":1784743200000,"ends_at":1784746800000},"summary":"Book Dan quote appointment."}'); const id=get(clerkDrafts)[0].id; await approveDraft(id); expect(get(clerkDrafts)[0].status).toBe('approved'); });
  it('creates a Launchpad link only after explicit approval', async () => { const url=`https://example.com/${crypto.randomUUID()}`; submitClerkInput('Add a Launchpad link'); appendClerkResponse(JSON.stringify({action:'create',object_type:'launchpad_link',payload:{id:'model-id',title:'Example',url},summary:'Add the link.'})); await approveDraft(get(clerkDrafts)[0].id); const links=await new PersistentCollection('launchpad_links').load(); expect(links.some((link)=>link.url===url&&link.title==='Example')).toBe(true); });
  it('creates a time log only after explicit approval', async () => { const startedAt=Date.now()-60000; submitClerkInput('Log time'); appendClerkResponse(JSON.stringify({action:'create',object_type:'time_log',payload:{id:'model-id',started_at:startedAt,ended_at:Date.now()},summary:'Record the time.'})); await approveDraft(get(clerkDrafts)[0].id); const logs=await new PersistentCollection('time_logs').load(); expect(logs.some((log)=>log.started_at===startedAt)).toBe(true); });
  it('creates a document through the shared Docs and Quicknotes model only after approval', async () => { const title=`Mango ${crypto.randomUUID()}`; submitClerkInput('Create a doc'); appendClerkResponse(JSON.stringify({action:'create',object_type:'document',payload:{id:'model-id',title,content:'Peel a mango'},summary:'Create the document.'})); await approveDraft(get(clerkDrafts)[0].id); expect(readJsonState<any[]>('dashboard.documents.v1',[]).some((doc)=>doc.title===title&&doc.content==='Peel a mango')).toBe(true); });
  it('removes an inline denied draft from history and the drafts tab', () => { submitClerkInput('Create a note'); appendClerkResponse('{"action":"create","object_type":"note","payload":{"title":"Mango"},"summary":"Create the note."}'); const draft=get(clerkDrafts)[0]; expect(get(clerkMessages).some((message)=>message.draft_id===draft.id)).toBe(true); denyDraft(draft.id); expect(get(clerkMessages).some((message)=>message.draft_id===draft.id)).toBe(false); });
  it('manages chat sessions and returns a selected history item to chat', () => { const id=newClerkChat(); submitClerkInput('What is on my calendar?'); expect(get(clerkSessions).some((session)=>session.id===id)).toBe(true); renameClerkChat(id,'Planning'); archiveClerkChat(id); expect(get(clerkSessions).find((session)=>session.id===id)?.archived).toBe(true); const second=newClerkChat(); selectClerkChat(second); expect(get(clerkPanelMode)).toBe('chat'); deleteClerkChat(second); expect(get(clerkSessions).some((session)=>session.id===second)).toBe(false); });
  it('always clears the active chat when starting a new chat', () => { const first=newClerkChat(); submitClerkInput('Keep this in the first chat'); const second=newClerkChat(); expect(second).not.toBe(first); expect(get(clerkMessages).filter((message)=>message.session_id===second)).toHaveLength(0); expect(get(clerkPanelMode)).toBe('chat'); });
  it('keeps prior sessions separate from a fresh active session', () => { const prior=newClerkChat(); submitClerkInput('Prior chat message'); const fresh=newClerkChat(); expect(get(clerkMessages).filter((message)=>message.session_id===fresh)).toHaveLength(0); expect(get(clerkMessages).filter((message)=>message.session_id===prior)).toHaveLength(1); });
});
