export interface ChatMessage { role:'system'|'user'|'assistant'; content:string; }
import { describeAIError } from './ai-errors';
export interface ClerkBaselineContext { now: string; timezone: string; projects: Array<{ id: string; name: string }>; currentProjectId: string | null; }
export function buildClerkContext(context: ClerkBaselineContext): string { return `Workspace context (authoritative for this request):\n- Current local date/time: ${context.now}\n- Timezone: ${context.timezone}\n- Projects: ${context.projects.length ? context.projects.map((project) => `${project.name} [${project.id}]`).join(', ') : 'No named projects yet'}\n- Current project scope: ${context.currentProjectId ?? 'all projects'}\n\nResolve relative dates and times such as today, tomorrow, next Tuesday, and this afternoon using the current local date/time and timezone. If a relative date is sufficiently clear, use the resolved ISO date in the JSON payload rather than asking the user to restate it.`; }
export function buildClerkConversation(messages: Array<{ role: 'user' | 'clerk'; content: string }>): ChatMessage[] { return messages.map((message) => ({ role: message.role === 'user' ? 'user' : 'assistant', content: message.content })); }
export async function askOllama(messages:ChatMessage[], endpoint='http://localhost:11434/v1/chat/completions', model='gemma4', apiKey=''):Promise<string>{const url=endpoint.replace(/\/$/,'').endsWith('/chat/completions')?endpoint:`${endpoint.replace(/\/$/,'')}/chat/completions`;let response:Response;try{response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json',...(apiKey?{Authorization:`Bearer ${apiKey}`}:{})},body:JSON.stringify({model,messages,stream:false})});}catch{throw new Error('Clerk AI could not connect. Check the AI endpoint in Settings → Advanced.');}if(!response.ok)throw describeAIError(response.status,'chat');const data=await response.json() as {choices?:Array<{message?:{content?:string}}>};return data.choices?.[0]?.message?.content??''}
export const clerkSystemPrompt=`You are Clerk, the AI assistant for the DeskClerk workspace. Answer questions about the user's projects, routines, documents, notes, links, events, tasks, time logs, and settings using the context provided by the application.

Never execute a mutation yourself. For every request to create, update, or delete any user-creatable object, your response MUST contain exactly one machine-readable JSON envelope in a fenced json block using this shape: {"action":"create|update|delete","object_type":"project|routine|document|note|link|launchpad_link|event|task|time_log|setting","payload":{},"summary":"A concise explanation of the proposed change and why it is being proposed."}

The payload must match the object's known application fields. If the object supports a title, always provide a useful title; infer one from the request when necessary. For project-scoped objects, always include the current project_id from workspace context. For updates and deletes, include the existing object's ID. For creates, omit ID entirely; the application generates it. If the request is partly vague but there is a reasonable safe interpretation, create a draft using that interpretation and put the uncertainty or clarifying question in the natural-language response and summary—do not withhold the draft. For example, an appointment mentioned as “next Tuesday at 1pm” should be drafted as a calendar event titled “Doctor's Appointment,” resolved in the user's timezone, with any missing details called out for confirmation. You may include natural-language explanation before or after the JSON, but never replace the JSON with Markdown pretending to be a draft. Do not call tools, storage, or APIs.`;
