import { writable } from 'svelte/store';
import { get } from 'svelte/store';
import type { ClerkCommand } from './commands';
import { PersistentCollection } from '../storage/persistent';
import { selectedProjectId } from '../projects/state';
import { hydrateJsonState, readJsonState, writeJsonState } from '../storage/json-state';
export interface ClerkMessage { id:string; role:'user'|'clerk'; content:string; created_at:number; command?:ClerkCommand['type']; draft_id?:string; session_id?:string; }
export interface ClerkSession { id:string; title:string; created_at:number; updated_at:number; archived:boolean; }
export interface ClerkProposal { action:'create'|'update'|'delete'; object_type:string; payload:Record<string, unknown>; summary:string; }
export interface ClerkDraft { id:string; action:ClerkProposal; created_at:number; status:'pending'|'denied'|'approved'; }
const historyKey='dashboard.clerk.history.v1'; const sessionKey='dashboard.clerk.sessions.v1'; const draftKey='dashboard.clerk.drafts.v1'; const load=<T>(key:string,fallback:T):T=>readJsonState(key,fallback); const save=(key:string,value:unknown)=>writeJsonState(key,value);
export const clerkMessages=writable<ClerkMessage[]>(load<ClerkMessage[]>(historyKey,[])); export const clerkSessions=writable<ClerkSession[]>(load<ClerkSession[]>(sessionKey,[])); export const currentClerkSessionId=writable<string|null>(null); export const clerkDrafts=writable<ClerkDraft[]>(load<ClerkDraft[]>(draftKey,[])); export const clerkProcessing=writable(false); export const clerkPanelMode=writable<'chat'|'drafts'|'history'>('chat');
void Promise.all([hydrateJsonState<ClerkMessage[]>(historyKey,[]), hydrateJsonState<ClerkSession[]>(sessionKey,[]), hydrateJsonState<ClerkDraft[]>(draftKey,[])]).then(([messages,sessions,drafts])=>{if(!get(clerkMessages).length)clerkMessages.set(messages);if(!get(clerkSessions).length)clerkSessions.set(sessions);if(!get(clerkDrafts).length)clerkDrafts.set(drafts)});
function ensureSession(title='New chat'){const sessions=load<ClerkSession[]>(sessionKey,[]);const active=get(currentClerkSessionId);if(active&&sessions.some((session)=>session.id===active&&!session.archived))return active;return createSession(title)}
function createSession(title='New chat'){const sessions=load<ClerkSession[]>(sessionKey,[]);const now=Date.now();const session={id:crypto.randomUUID(),title,created_at:now,updated_at:now,archived:false};save(sessionKey,[...sessions,session]);clerkSessions.set([...sessions,session]);currentClerkSessionId.set(session.id);return session.id}
export function newClerkChat(){const id=createSession();clerkPanelMode.set('chat');return id}
export function selectClerkChat(id:string){if(!get(clerkSessions).some((session)=>session.id===id&&!session.archived))return;currentClerkSessionId.set(id);clerkPanelMode.set('chat')}
export function renameClerkChat(id:string,title:string){const next=get(clerkSessions).map((session)=>session.id===id?{...session,title:title.trim()||'Untitled chat',updated_at:Date.now()}:session);save(sessionKey,next);clerkSessions.set(next)}
export function archiveClerkChat(id:string){const next=get(clerkSessions).map((session)=>session.id===id?{...session,archived:true}:session);save(sessionKey,next);clerkSessions.set(next);if(get(currentClerkSessionId)===id)currentClerkSessionId.set(null)}
export function deleteClerkChat(id:string){const sessions=get(clerkSessions).filter((session)=>session.id!==id);const messages=load<ClerkMessage[]>(historyKey,[]).filter((message)=>message.session_id!==id);save(sessionKey,sessions);save(historyKey,messages);clerkSessions.set(sessions);clerkMessages.set(messages);if(get(currentClerkSessionId)===id)currentClerkSessionId.set(null)}
export function submitClerkInput(input:string):ClerkMessage[]{const sessionId=ensureSession(input.trim().slice(0,40));const message={id:crypto.randomUUID(),role:'user' as const,content:input.trim(),created_at:Date.now(),session_id:sessionId};const next=[...load<ClerkMessage[]>(historyKey,[]),message];save(historyKey,next);clerkMessages.set(next);return [message]}
function extractProposal(content:string):{proposal:ClerkProposal; visible:string}|undefined{const match=content.match(/```json\s*([\s\S]*?)```|({\s*"action"\s*:[\s\S]*})/i);if(!match)return;try{const raw=JSON.parse(match[1]??match[2]);if(!['create','update','delete'].includes(raw.action)||typeof raw.object_type!=='string'||!raw.payload||typeof raw.payload!=='object')return;return {proposal:{action:raw.action,object_type:raw.object_type,payload:raw.payload,summary:typeof raw.summary==='string'?raw.summary:'Proposed workspace change.'},visible:content.replace(match[0],'').trim()}}catch{return}}
export function appendClerkResponse(content:string){const sessionId=ensureSession();const parsed=extractProposal(content);const now=Date.now();if(parsed?.proposal.action==='create'){const projectId=get(selectedProjectId);if(projectId&&['project','setting'].includes(parsed.proposal.object_type)===false&&parsed.proposal.payload.project_id===undefined)parsed.proposal.payload.project_id=projectId;}const draft=parsed?{id:crypto.randomUUID(),action:parsed.proposal,created_at:now,status:'pending' as const}:undefined;const message={id:crypto.randomUUID(),role:'clerk' as const,content:parsed?.visible??content,created_at:now,session_id:sessionId,draft_id:draft?.id};const next=[...load<ClerkMessage[]>(historyKey,[]),message];save(historyKey,next);clerkMessages.set(next);if(draft){const drafts=[...load<ClerkDraft[]>(draftKey,[]),draft];save(draftKey,drafts);clerkDrafts.set(drafts)}}
export function denyDraft(id:string){const next=load<ClerkDraft[]>(draftKey,[]).map((draft)=>draft.id===id?{...draft,status:'denied' as const}:draft);save(draftKey,next);clerkDrafts.set(next);const messages=load<ClerkMessage[]>(historyKey,[]).filter((message)=>message.draft_id!==id);save(historyKey,messages);clerkMessages.set(messages)}
export async function approveDraft(id:string){const draft=get(clerkDrafts).find((item)=>item.id===id);if(!draft||draft.status!=='pending')return;const projectId=get(selectedProjectId)??'default';const payload={...draft.action.payload};delete payload.id;if(draft.action.action==='create'&&draft.action.object_type==='task')await new PersistentCollection('tasks').create({...payload,project_id:payload.project_id??projectId} as never);else if(draft.action.action==='create'&&draft.action.object_type==='event'){const starts_at=Number(payload.starts_at??payload.start_at??payload.start);const ends_at=Number(payload.ends_at??payload.end_at??payload.end);if(!Number.isFinite(starts_at)||!Number.isFinite(ends_at))throw new Error('Event draft is missing valid start and end times');await new PersistentCollection('events').create({title:String(payload.title??'Untitled event'),description:payload.description ? String(payload.description) : undefined,location:payload.location ? String(payload.location) : undefined,project_id:String(payload.project_id??projectId),starts_at,ends_at,all_day:Boolean(payload.all_day??false),repeat:(payload.repeat as never)??'none',completed:false,source_type:'manual',read_only:false} as never);}else if(draft.action.action==='create'&&['link','launchpad_link'].includes(draft.action.object_type)){if(!payload.url)throw new Error('Launchpad link draft is missing a URL');await new PersistentCollection('launchpad_links').create({title:String(payload.title??payload.url),url:String(payload.url),project_id:String(payload.project_id??projectId),tags:Array.isArray(payload.tags)?payload.tags:[],description:payload.description?String(payload.description):undefined,icon_color:payload.icon_color?String(payload.icon_color):undefined,pinned:false,blurred:false,archived:false,position:0} as never);}else if(draft.action.action==='create'&&draft.action.object_type==='time_log'){const started_at=Number(payload.started_at);const ended_at=payload.ended_at===undefined?undefined:Number(payload.ended_at);if(!Number.isFinite(started_at))throw new Error('Time log draft is missing a valid start time');await new PersistentCollection('time_logs').create({project_id:String(payload.project_id??projectId),started_at,ended_at,duration_seconds:Number(payload.duration_seconds??(ended_at===undefined?0:Math.max(0,(ended_at-started_at)/1000)))} as never);}else if(draft.action.action==='create'&&(draft.action.object_type==='note'||draft.action.object_type==='document')){const key='dashboard.documents.v1';const existing=load<any[]>(key,[]);const now=Date.now();save(key,[...existing,{...payload,id:crypto.randomUUID(),project_id:payload.project_id??projectId,created_at:now,updated_at:now}]);}const next=get(clerkDrafts).map((item)=>item.id===id?{...item,status:'approved' as const}:item);save(draftKey,next);clerkDrafts.set(next)}
export function clearClerkHistory(){clerkMessages.set([]);clerkSessions.set([]);currentClerkSessionId.set(null);clerkDrafts.set([]);save(historyKey,[]);save(sessionKey,[]);save(draftKey,[])}
