<script lang="ts">
  import { monthLabel, monthMatrix, populateMonth, filterCalendarItems } from '../calendar/calendar';
  import { taskDurationIsUnderDay, timeLogFromEvent, type CalendarTask } from '../calendar/tasks';
  import type { CalendarEvent } from '../calendar/events'; import { openCalendarRequest } from '../calendar/open';
  import EventModal from './EventModal.svelte'; import TaskModal from './TaskModal.svelte'; import { onMount } from 'svelte'; import { PersistentCollection } from '../storage/persistent'; import { selectedProjectId, projectViewMode } from '../projects/state'; import { logFromCalendarEvent, startTimer } from '../time/state';
  export let projectId: string | undefined; export let items: CalendarEvent[] = []; export let onChange: (items: CalendarEvent[]) => void = () => undefined;
  const weekdays = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']; const persistedTasks = new PersistentCollection('tasks'); const persistedEvents = new PersistentCollection('events'); const persistedLogs = new PersistentCollection('time_logs'); let current = new Date(); let tasks: CalendarTask[] = []; let selectedDate = ''; let modal: 'event' | 'task' | undefined; let mode: 'create' | 'detail' | 'edit' = 'create'; let selectedEvent: CalendarEvent | undefined; let selectedTask: CalendarTask | undefined;
  $: scopedProjectId = projectId ?? ($projectViewMode === 'project' ? ($selectedProjectId ?? undefined) : undefined);
  onMount(async () => { const unsubscribe = openCalendarRequest.subscribe((request) => { if (request) { open(request); openCalendarRequest.set(null); } }); try { tasks = await persistedTasks.load(scopedProjectId); items = await persistedEvents.load(scopedProjectId) as CalendarEvent[]; } catch { tasks = []; items = []; } return unsubscribe; });
  $: if ($projectViewMode || $selectedProjectId) void reloadScope(scopedProjectId);
  async function reloadScope(scope?: string): Promise<void> { try { tasks = await persistedTasks.load(scope); items = await persistedEvents.load(scope) as CalendarEvent[]; } catch { tasks = []; items = []; } }
  $: days = populateMonth(monthMatrix(current.getFullYear(), current.getMonth()), filterCalendarItems([...items.filter((item) => !scopedProjectId || item.project_id === scopedProjectId), ...tasks.filter((task) => !scopedProjectId || task.project_id === scopedProjectId).map((task) => ({ ...task, starts_at: task.due_at, kind: 'task' as const }))], scopedProjectId)); $: label = monthLabel(current.getFullYear(), current.getMonth());
  function createEvent(date: string): void { selectedDate = date; selectedEvent = undefined; modal = 'event'; mode = 'create'; }
  function createTask(date: string): void { selectedDate = date; selectedTask = undefined; modal = 'task'; mode = 'create'; }
  function open(item: CalendarEvent | CalendarTask): void { if ('due_at' in item) { selectedTask = item; modal = 'task'; } else { selectedEvent = item; modal = 'event'; } mode = 'detail'; }
  async function saveEvent(event: CalendarEvent): Promise<void> { const exists = items.some((item) => item.id === event.id); const stored = exists ? await persistedEvents.update(event as never) : await persistedEvents.create(event as never); const next = exists ? items.map((item) => item.id === event.id ? stored as CalendarEvent : item) : [...items, stored as CalendarEvent]; items = next; onChange(next); modal = undefined; }
  async function saveTask(task: CalendarTask): Promise<void> { const exists = tasks.some((item) => item.id === task.id); const stored = exists ? await persistedTasks.update(task as never) : await persistedTasks.create({ ...task, notes: task.description } as never); tasks = exists ? tasks.map((item) => item.id === task.id ? stored as CalendarTask : item) : [...tasks, stored as CalendarTask]; modal = undefined; }
  async function completeTask(task: CalendarTask): Promise<void> { const updated = { ...task, completed: !task.completed }; await persistedTasks.update(updated as never); tasks = tasks.map((item) => item.id === task.id ? updated : item); }
  function startTaskTimer(task: CalendarTask): void { startTimer(task.title, task.description ?? '', task.project_id, task.id); }
  async function toggleTask(task: CalendarTask): Promise<void> { const updated = { ...task, blurred: !task.blurred }; await persistedTasks.update(updated as never); tasks = tasks.map((item) => item.id === task.id ? updated : item); }
  async function toggleEvent(event: CalendarEvent): Promise<void> { const updated = { ...event, blurred: !event.blurred }; await persistedEvents.update(updated as never); items = items.map((item) => item.id === event.id ? updated : item); onChange(items); }
  async function completeEvent(event: CalendarEvent): Promise<void> { const updated = { ...event, completed: !event.completed }; await persistedEvents.update(updated as never); items = items.map((item) => item.id === event.id ? updated : item); if (updated.completed && updated.ends_at && taskDurationIsUnderDay(updated.starts_at, updated.ends_at)) logFromCalendarEvent(updated as CalendarEvent & { ends_at: number }); }
  async function deleteEvent(event: CalendarEvent): Promise<void> { await persistedEvents.softDelete(event.id); items = items.filter((item) => item.id !== event.id); onChange(items); modal = undefined; }
  async function deleteTask(task: CalendarTask): Promise<void> { await persistedTasks.softDelete(task.id); tasks = tasks.filter((item) => item.id !== task.id); modal = undefined; }
</script>
<div class="calendar-view" aria-label="Calendar"><div class="calendar-toolbar"><div class="month-controls"><button aria-label="Previous month" on:click={() => current = new Date(current.getFullYear(), current.getMonth() - 1, 1)}>‹</button><button aria-label="Next month" on:click={() => current = new Date(current.getFullYear(), current.getMonth() + 1, 1)}>›</button><h4>{label}</h4><button on:click={() => current = new Date()}>Today</button></div><span>{projectId ? 'This project' : 'All projects'}</span></div><div class="weekday-row">{#each weekdays as weekday}<span>{weekday}</span>{/each}</div><div class="calendar-grid">{#each days as day}<article class:outside={!day.inMonth} class="calendar-cell"><div class="cell-header"><span>{day.day}</span><div><button aria-label={`Create task on ${day.isoDate}`} on:click={() => createTask(day.isoDate)}>☐</button><button aria-label={`Create event on ${day.isoDate}`} on:click={() => createEvent(day.isoDate)}>+</button></div></div>{#each day.items as item}{#if item.kind === 'task'}<div class:completed={(item as CalendarTask).completed} class:blurred={(item as CalendarTask).blurred} class="calendar-item"><input type="checkbox" checked={(item as CalendarTask).completed} on:change={() => completeTask(item as CalendarTask)} /><button on:click={() => open(item as CalendarTask)}>{item.title}</button><button class="item-obfuscate" aria-label={item.blurred ? "Unblur task" : "Blur task"} on:click|stopPropagation={() => toggleTask(item as CalendarTask)}><img src={`/tmp-icons/${item.blurred ? "obfuscated" : "obfuscation"}.svg`} alt="" /></button></div>{:else}<div class:completed={(item as CalendarEvent).completed} class:blurred={(item as CalendarEvent).blurred} class="calendar-item"><input type="checkbox" checked={(item as CalendarEvent).completed} disabled={!taskDurationIsUnderDay(item.starts_at, item.ends_at)} on:change={() => completeEvent(item as CalendarEvent)} /><button on:click={() => open(item as CalendarEvent)}>{item.title}</button><button class="item-obfuscate" aria-label={item.blurred ? "Unblur event" : "Blur event"} on:click|stopPropagation={() => toggleEvent(item as CalendarEvent)}><img src={`/tmp-icons/${item.blurred ? "obfuscated" : "obfuscation"}.svg`} alt="" /></button></div>{/if}{/each}</article>{/each}</div>{#if modal === 'event'}<EventModal mode={mode} event={selectedEvent} date={new Date(`${selectedDate}T00:00:00`)} projectId={projectId ?? 'default'} on:save={(event) => saveEvent(event.detail)} on:delete={(event) => deleteEvent(event.detail)} on:close={() => modal = undefined} />{:else if modal === 'task'}<TaskModal mode={mode} task={selectedTask} date={new Date(`${selectedDate}T00:00:00`)} projectId={projectId ?? 'default'} on:save={(task) => saveTask(task.detail)} on:delete={(task) => deleteTask(task.detail)} on:start={(task) => console.info('timer started', task.detail.id)} on:close={() => modal = undefined} />{/if}</div>
<style>.calendar-view { padding: .25rem 0; } .calendar-toolbar, .month-controls, .cell-header { display: flex; align-items: center; } .calendar-toolbar { justify-content: space-between; margin-bottom: 1rem; } .month-controls { gap: .45rem; } h4 { margin: 0 .5rem; } .calendar-toolbar button, .cell-header button { padding: .35rem .5rem; border: 1px solid var(--border-custom); border-radius: .35rem; background: var(--bg-elevated); color: var(--text-main); cursor: pointer; } .weekday-row, .calendar-grid { display: grid; grid-template-columns: repeat(7, minmax(0, 1fr)); } .weekday-row { color: var(--text-muted); font-size: .72rem; text-transform: uppercase; } .weekday-row span { padding: .45rem; } .calendar-cell { min-height: 7rem; padding: .5rem; border: 1px solid var(--border-custom); background: var(--bg-primary); } .calendar-cell.outside { background: var(--bg-secondary); color: var(--text-muted); } .cell-header { justify-content: space-between; } .cell-header div { display: flex; gap: .2rem; opacity: 0; pointer-events: none; transition: opacity .15s ease; } .calendar-cell:hover .cell-header div, .calendar-cell:focus-within .cell-header div { opacity: 1; pointer-events: auto; } .cell-header button { padding: .15rem .3rem; } .calendar-item { display: flex; align-items: center; gap: .25rem; margin-top: .45rem; padding: .25rem; border-left: 3px solid var(--accent-primary); border-radius: .2rem; background: var(--accent-secondary); font-size: .72rem; } .calendar-item button { overflow: hidden; flex: 1; border: 0; background: transparent; color: inherit; cursor: pointer; text-align: left; text-overflow: ellipsis; white-space: nowrap; } .calendar-item .item-obfuscate { flex: 0 0 auto; width: 1.5rem; padding: .15rem; opacity: 0; } .calendar-item:hover .item-obfuscate, .calendar-item:focus-within .item-obfuscate { opacity: 1; } .item-obfuscate img { width: 1rem; height: 1rem; } .calendar-item.completed button { text-decoration: line-through; opacity: .6; } .calendar-item input { width: .9rem; } @media (max-width: 720px) { .calendar-cell { min-height: 4.5rem; padding: .25rem; } }
</style>
