<script lang="ts">
  import { submitClerkInput, appendClerkResponse, approveDraft, denyDraft, clerkDrafts, clerkMessages, clerkProcessing, currentClerkSessionId } from '../clerk/state';
  import { askOllama, buildClerkContext, buildClerkConversation, clerkSystemPrompt } from '../clerk/ollama';
  import { get } from 'svelte/store';
  import { projects, selectedProjectId } from '../projects/state';
  import { currentClerkAIConfig } from '../clerk/ai-config';
  import { transcribeAudio } from '../clerk/transcribe';
  let prompt = '';
  let recorder: MediaRecorder | undefined; let chunks: Blob[] = []; let recording = false;
  let aiError = '';
  async function submit(text = prompt): Promise<void> { const input = text.trim(); if (!input || $clerkProcessing) return; aiError = ''; submitClerkInput(input); prompt = ''; clerkProcessing.set(true); try { const now = new Date(); const context = buildClerkContext({ now: now.toLocaleString(), timezone: Intl.DateTimeFormat().resolvedOptions().timeZone, projects: get(projects).filter((project) => !project.deleted_at).map((project) => ({ id: project.id, name: project.name })), currentProjectId: get(selectedProjectId) }); const conversation = get(clerkMessages).filter((message) => !$currentClerkSessionId || message.session_id === $currentClerkSessionId); const config = currentClerkAIConfig(); const messages = [{ role: 'system' as const, content: clerkSystemPrompt }, { role: 'system' as const, content: context }, ...buildClerkConversation(conversation)]; const reply = await askOllama(messages, config.endpoint, config.model, config.apiKey); if (reply.trim()) appendClerkResponse(reply.trim()); } catch (cause) { aiError = cause instanceof Error ? cause.message : 'Clerk AI request failed. Check Settings → Advanced.'; } finally { clerkProcessing.set(false); } }
  async function startRecording(): Promise<void> { if (recording || !navigator.mediaDevices?.getUserMedia) return; const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); recorder = new MediaRecorder(stream); chunks = []; recorder.ondataavailable = (event) => { if (event.data.size) chunks.push(event.data); }; recorder.onstop = async () => { stream.getTracks().forEach((track) => track.stop()); try { const text = await transcribeAudio(new Blob(chunks, { type: recorder?.mimeType || 'audio/webm' }), currentClerkAIConfig()); if (text) await submit(text); } catch (cause) { aiError = cause instanceof Error ? cause.message : 'Voice transcription failed. Check Settings → Advanced.'; } }; recorder.start(); recording = true; }
  function stopRecording(): void { if (!recorder || !recording) return; recorder.stop(); recording = false; }
</script>

<div class="clerk-panel">
  <div class="message-list" aria-live="polite">
    {#each $clerkMessages.filter((message) => !$currentClerkSessionId || message.session_id === $currentClerkSessionId) as message (message.id)}
      <div class:from-user={message.role === 'user'} class="message"><span>{message.role === 'user' ? 'You' : 'Clerk'}</span><p>{message.content}</p>{#if message.draft_id}{#each $clerkDrafts.filter((item) => item.id === message.draft_id && item.status === 'pending') as draft}<div class="draft-card"><strong>{draft.action.action.toUpperCase()} {draft.action.object_type.toUpperCase()} DRAFT</strong><p>{draft.action.summary}</p><pre>{JSON.stringify(draft.action.payload, null, 2)}</pre><div><button on:click={() => approveDraft(draft.id)}>Approve</button><button on:click={() => denyDraft(draft.id)}>Deny</button></div></div>{/each}{/if}</div>
    {/each}
    {#if $clerkProcessing}<div class="generating" role="status" aria-label="Clerk is generating a response"><span></span><span></span><span></span><em>Clerk is thinking…</em></div>{:else if !$clerkMessages.filter((message) => !$currentClerkSessionId || message.session_id === $currentClerkSessionId).length}<p class="empty-prompt">Ask Clerk about your DeskClerk workspace.</p>{/if}
  </div>
  <form class="prompt-form" on:submit|preventDefault={() => submit()}><input aria-label="Ask Clerk" bind:value={prompt} placeholder="Ask Clerk…" /><button class:recording aria-label="Hold to speak" type="button" on:pointerdown={startRecording} on:pointerup={stopRecording} on:pointerleave={stopRecording}><img src={`/tmp-icons/${recording ? 'microphone-hot' : 'microphone'}.svg`} alt="" /></button><button aria-label="Send to Clerk" type="submit">↑</button></form>
  {#if aiError}<p class="ai-error" role="alert">{aiError}</p>{/if}
</div>

<style>
  .clerk-panel{display:grid;grid-template-rows:minmax(0,1fr) auto;gap:.7rem;min-height:0;height:100%;overflow:hidden}.message-list{display:grid;align-content:start;gap:.55rem;min-height:0;overflow-y:auto;padding:.25rem .1rem}.empty-prompt{align-self:center;margin:auto;color:var(--text-muted);font-size:.85rem}.message{padding:.65rem .75rem;border:1px solid var(--border-custom);border-radius:.55rem;background:var(--accent-secondary);font-size:.78rem}.message.from-user{background:var(--bg-elevated)}.message span{color:var(--text-muted);font-size:.68rem}.message p{margin:.25rem 0 0;white-space:pre-wrap}.draft-card{margin-top:.6rem;padding:.65rem;border:1px solid var(--border-custom);border-radius:.45rem;background:var(--bg-primary)}.draft-card strong{font-size:.7rem}.draft-card pre{max-height:8rem;overflow:auto;white-space:pre-wrap;color:var(--text-muted);font-size:.68rem}.draft-card button{width:auto;margin-right:.35rem;padding:.4rem .6rem}.generating{display:flex;align-items:center;gap:.25rem;color:var(--text-muted);font-size:.75rem}.generating span{width:.4rem;height:.4rem;border-radius:50%;background:var(--text-muted);animation:pulse 1s infinite alternate}.generating span:nth-child(2){animation-delay:.2s}.generating span:nth-child(3){animation-delay:.4s}.generating em{margin-left:.3rem;font-style:normal}@keyframes pulse{to{opacity:.25;transform:translateY(-2px)}}.prompt-form{display:flex;gap:.4rem;padding-top:.6rem;border-top:1px solid var(--border-custom)}input{min-width:0;flex:1;padding:.7rem;border:1px solid var(--border-custom);border-radius:.45rem;background:var(--bg-elevated);color:var(--text-main);font:inherit}button{border:1px solid var(--border-custom);border-radius:.45rem;background:var(--accent-primary);color:var(--text-inverse);cursor:pointer}.prompt-form button{display:grid;place-items:center;width:2.8rem;height:2.8rem;padding:.55rem}.prompt-form button img{width:1.15rem;height:1.15rem;filter:invert(1)}.prompt-form button.recording{background:#b83d4d}.prompt-form button[type='submit']{font-size:1.35rem;line-height:1}
</style>
