<script lang="ts">
  import { createProject } from '../projects/state';
  import { createEventDispatcher, onMount } from 'svelte';
  const dispatch = createEventDispatcher<{ close: void; created: void }>(); let name = ''; let error = '';
  import { showToast } from '../ui/toast';
  function submit(): void { try { createProject(name); showToast('Project created.'); dispatch('created'); dispatch('close'); } catch (cause) { error = cause instanceof Error ? cause.message : 'Unable to create project'; showToast(error, 'error'); } }
  onMount(() => { const handler = (event: KeyboardEvent) => event.key === 'Escape' && dispatch('close'); window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler); });
</script>
<div class="backdrop" role="presentation" on:click={(event) => event.target === event.currentTarget && dispatch('close')}><section class="modal" role="dialog" aria-modal="true" aria-label="Create project"><header><h3>New Project</h3><button aria-label="Close" on:click={() => dispatch('close')}>×</button></header><form on:submit|preventDefault={submit}><label>Project name<input aria-label="Project name" bind:value={name} autofocus placeholder="e.g. Personal" /></label>{#if error}<p class="error">{error}</p>{/if}<footer><button type="button" class="secondary" on:click={() => dispatch('close')}>Cancel</button><button type="submit">Create project</button></footer></form></section></div>
<style>.backdrop { position: fixed; z-index: 30; inset: 0; display: grid; place-items: center; background: rgb(0 0 0 / .55); } .modal { width: min(28rem, calc(100vw - 2rem)); border: 1px solid var(--border-custom); border-radius: .7rem; background: var(--bg-primary); color: var(--text-main); } header, footer { display: flex; align-items: center; justify-content: space-between; gap: .5rem; } header { padding: 1rem 1.2rem; border-bottom: 1px solid var(--border-custom); } h3 { margin: 0; } header button { border: 0; background: transparent; color: inherit; font-size: 1.4rem; } form { display: grid; gap: 1rem; padding: 1.2rem; } label { display: grid; gap: .4rem; color: var(--text-muted); font-size: .8rem; } input { padding: .65rem; border: 1px solid var(--border-custom); border-radius: .4rem; background: var(--bg-elevated); color: var(--text-main); } footer { justify-content: flex-end; padding-top: .8rem; border-top: 1px solid var(--border-custom); } footer button { padding: .55rem .7rem; border: 1px solid var(--border-custom); border-radius: .4rem; background: var(--accent-primary); color: var(--text-inverse); cursor: pointer; } footer .secondary { background: var(--bg-secondary); color: var(--text-main); } .error { color: #c84d5d; }</style>
