<script lang="ts">
  import type { ClerkAIConfig, CloudSyncConfig } from '../integrations/custom-ai';
  export let cloud: CloudSyncConfig = { baseUrl: '', apiToken: '' };
  export let ai: ClerkAIConfig = { endpoint: '', apiKey: '', model: 'gpt-4o-mini', maxTokens: 2048, transcriptionModel: 'gpt-4o-mini-transcribe' };
  export let onChange: (cloud: CloudSyncConfig, ai: ClerkAIConfig) => void = () => undefined;
</script>
<section class="ai-settings"><h4>Custom AI and API endpoints</h4><p>Keys are used only for the endpoint you specify and are never displayed in logs.</p><label>Cloud sync base URL<input bind:value={cloud.baseUrl} placeholder="https://your-sync.example/api" /></label><label>Cloud sync API token<input type="password" bind:value={cloud.apiToken} /></label><label>Clerk AI endpoint<input bind:value={ai.endpoint} placeholder="https://your-llm.example/v1/chat/completions" /></label><label>Clerk AI API key<input type="password" bind:value={ai.apiKey} /></label><div class="two-col"><label>AI model<input bind:value={ai.model} /></label><label>Max tokens<input type="number" min="1" bind:value={ai.maxTokens} /></label></div><label>Transcription model<input bind:value={ai.transcriptionModel} /></label><button on:click={() => onChange(cloud, ai)}>Save custom endpoints</button></section>
<style>
  .ai-settings { display: grid; gap: .65rem; padding: 1.5rem 0; border-top: 1px solid var(--border-custom); } h4 { margin: 0; } p { margin: 0; color: var(--text-muted); font-size: .8rem; } label { display: grid; gap: .3rem; color: var(--text-muted); font-size: .72rem; } input { padding: .55rem; border: 1px solid var(--border-custom); border-radius: .4rem; background: var(--bg-elevated); color: var(--text-main); } button { width: fit-content; padding: .55rem .7rem; border: 1px solid var(--border-custom); border-radius: .4rem; background: var(--accent-primary); color: var(--text-inverse); cursor: pointer; } .two-col { display: grid; grid-template-columns: 1fr 1fr; gap: .6rem; } @media (max-width: 600px) { .two-col { grid-template-columns: 1fr; } }
</style>
