<script lang="ts">
  import { createEventDispatcher, onMount } from 'svelte';
  import { draftFromEvent, eventFromDraft, validateEventDraft, type CalendarEvent, type EventDraft } from '../calendar/events';
  import { projects } from '../projects/state';
  export let mode: 'create' | 'detail' | 'edit' = 'create'; export let event: CalendarEvent | undefined; export let date = new Date(); export let projectId = 'default';
  const dispatch = createEventDispatcher<{ save: CalendarEvent; delete: CalendarEvent; close: void }>();
  let draft: EventDraft = { project_id: projectId, title: '', description: '', location: '', starts_at: '', ends_at: '', all_day: false, repeat: 'none', source_type: 'manual', read_only: false }; let error = ''; let blurred = false;
  $: if (event && mode !== 'create' && !draft.title) { draft = draftFromEvent(event); blurred = event.blurred ?? false; }
  $: if (mode === 'create' && !draft.starts_at) { const start = new Date(date); start.setHours(9, 0, 0, 0); const end = new Date(start); end.setHours(10); draft = { ...draft, starts_at: toInput(start), ends_at: toInput(end) }; }
  function toInput(value: Date): string { const pad = (number: number) => String(number).padStart(2, '0'); return `${value.getFullYear()}-${pad(value.getMonth() + 1)}-${pad(value.getDate())}T${pad(value.getHours())}:${pad(value.getMinutes())}`; }
  function save(): void { error = validateEventDraft(draft) ?? ''; if (!error) dispatch('save', { ...eventFromDraft(draft, event?.id), blurred }); }
  function close(): void { dispatch('close'); } function onBackdrop(e: MouseEvent): void { if (e.target === e.currentTarget) close(); } function keydown(e: KeyboardEvent): void { if (e.key === 'Escape') close(); }
  onMount(() => { window.addEventListener('keydown', keydown); return () => window.removeEventListener('keydown', keydown); });
</script>
<div class="modal-backdrop" role="presentation" on:click={onBackdrop}><section class="event-modal" role="dialog" aria-modal="true" aria-labelledby="event-modal-title" on:click|stopPropagation><header><h3 id="event-modal-title">{mode === 'create' ? 'Add Event' : mode === 'edit' ? 'Edit Event' : event?.title}</h3><button class="close-x" aria-label="Close" on:click={close}>×</button></header>{#if mode === 'detail' && event}<div class="details"><p class="detail-title obfuscate-target">{event.title}</p>{#if event.description}<p class="detail-copy">{event.description}</p>{/if}<p><strong>Project</strong><br />{$projects.find((item) => item.id === event.project_id)?.name ?? event.project_id}</p><p><strong>Starts</strong><br />{new Date(event.starts_at).toLocaleString()}</p>{#if event.ends_at}<p><strong>Ends</strong><br />{new Date(event.ends_at).toLocaleString()}</p>{/if}<footer><button class="secondary" on:click={close}>Close</button>{#if !event.read_only}<button on:click={() => mode = 'edit'}>Edit</button><button class="danger" on:click={() => dispatch('delete', event)}>Delete</button>{/if}</footer></div>{:else}<form on:submit|preventDefault={save}><label>Title *<input aria-label="Event title" bind:value={draft.title} autofocus /></label><label>Description<textarea aria-label="Event description" bind:value={draft.description}></textarea></label><div class="two-col"><label>Start Date *<input type="datetime-local" aria-label="Start date" bind:value={draft.starts_at} /></label><label>End Date<input type="datetime-local" aria-label="End date" bind:value={draft.ends_at} /></label></div><label>Location<input aria-label="Event location" bind:value={draft.location} /></label><label>Repeat<select aria-label="Event repeat" bind:value={draft.repeat}><option value="none">Does not repeat</option><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select><small>Choose how often this event repeats.</small></label><label>Project<select aria-label="Event project" bind:value={draft.project_id}>{#each $projects.filter((item) => !item.deleted_at) as project}<option value={project.id}>{project.name}</option>{/each}<option value="default">Default project</option></select><small>Choose which project this event belongs to.</small></label><label class="check"><input type="checkbox" bind:checked={draft.all_day} /> All day event</label>{#if error}<p class="error" role="alert">{error}</p>{/if}<footer><button type="button" class="secondary" on:click={close}>Cancel</button><button type="submit">{mode === 'edit' ? 'Save Changes' : 'Add Event'}</button></footer></form>{/if}</section></div>
<style>
  .modal-backdrop{position:fixed!important;z-index:1000;inset:0;display:grid;place-items:center;overflow:auto;padding:1rem;background:rgb(18 24 38/.58)}.event-modal{width:min(42rem,100%);max-height:calc(100vh - 2rem);overflow:auto;margin:auto;border:1px solid var(--border-custom);border-radius:.7rem;background:var(--bg-primary);color:var(--text-main);box-shadow:0 1.5rem 4rem rgb(0 0 0/.25)}header{display:flex;align-items:center;justify-content:space-between;padding:1.2rem 1.5rem;border-bottom:1px solid var(--border-custom)}h3{margin:0;font-size:1.35rem}.close-x{border:0;background:transparent;color:var(--text-main);font-size:1.6rem;cursor:pointer}form,.details{display:grid;gap:1rem;padding:1.5rem}label{display:grid;gap:.35rem;color:var(--text-muted);font-size:.8rem}input,textarea,select{width:100%;padding:.65rem .7rem;border:1px solid var(--border-custom);border-radius:.35rem;background:var(--bg-elevated);color:var(--text-main);font:inherit}textarea{min-height:5rem;resize:vertical}small{color:var(--text-muted)}.two-col{display:grid;grid-template-columns:1fr 1fr;gap:.8rem}.check{display:flex;align-items:center;gap:.45rem}.check input{width:auto}footer{display:flex;justify-content:flex-end;gap:.5rem;padding-top:.8rem;border-top:1px solid var(--border-custom)}button{padding:.6rem .8rem;border:1px solid var(--border-custom);border-radius:.4rem;background:var(--accent-primary);color:var(--text-inverse);cursor:pointer}button.secondary{background:var(--bg-secondary);color:var(--text-main)}button.danger{background:#9b3544}.details p{margin:0;color:var(--text-muted);line-height:1.5}.detail-title{color:var(--text-main)!important;font:700 1.2rem 'Grenze Gotisch',serif}.detail-copy{white-space:pre-wrap}.error{margin:0;color:#a22b3f;font-size:.8rem}@media(max-width:600px){.two-col{grid-template-columns:1fr}}
</style>
