<script lang="ts">
  import { onMount } from 'svelte';
  import { createLaunchpadLinkRequest } from '../launchpad/open';
  import { parseLinkInput, filterLinks, allTags } from '../launchpad/links';
  import { faviconUrl, reorderLinks, toggleLinkFlag } from '../launchpad/actions';
  import { PersistentCollection } from '../storage/persistent';
  import type { LaunchpadLink } from '../storage/models'; import { selectedProjectId } from '../projects/state'; import { launchpadScope } from '../projects/view-scopes'; import ScopeToggle from './ScopeToggle.svelte';
  import { showToast } from '../ui/toast';
  export let projectId: string | undefined;
  const persisted = new PersistentCollection('launchpad_links');
  let links: LaunchpadLink[] = []; let url = ''; let title = ''; let tags = ''; let selectedTag = ''; let error = ''; let dragged = -1; let editing: LaunchpadLink | undefined; let menu: string | null = null; let createOpen = false;
  $: visibleLinks = filterLinks(links.filter((link) => !link.archived), '', selectedTag || undefined);
  $: pinnedLinks = visibleLinks.filter((link) => link.pinned); $: otherLinks = visibleLinks.filter((link) => !link.pinned); $: tagsList = allTags(links);
  $: scopedProjectId = projectId ?? ($launchpadScope === 'project' ? ($selectedProjectId ?? undefined) : undefined);
  onMount(async () => { const unsubscribe = createLaunchpadLinkRequest.subscribe((request) => { if (request) { error = ''; createOpen = true; createLaunchpadLinkRequest.set(false); } }); try { links = await persisted.load(scopedProjectId); } catch { links = []; } return unsubscribe; });
  $: if (scopedProjectId !== undefined || $launchpadScope) void reloadLinks(scopedProjectId);
  async function reloadLinks(scope?: string): Promise<void> { try { links = await persisted.load(scope); } catch { links = []; } }
  async function addLink() { try { const input = parseLinkInput(url, title, tags, scopedProjectId ?? 'default'); const saved = await persisted.create({ ...input, blurred: false, pinned: false, archived: false, position: links.length }); links = [saved, ...links]; url = ''; title = ''; tags = ''; error = ''; createOpen = false; showToast('Link added.'); } catch (cause) { error = cause instanceof Error ? cause.message : 'Unable to add link'; showToast(error, 'error'); } }
  async function toggle(link: LaunchpadLink, flag: 'blurred' | 'pinned') { const updated = await persisted.update(toggleLinkFlag(link, flag)); links = links.map((item) => item.id === link.id ? updated : item); menu = null; }
  async function archive(link: LaunchpadLink) { const updated = await persisted.update({ ...link, archived: !link.archived }); links = links.map((item) => item.id === link.id ? updated : item); menu = null; }
  async function remove(link: LaunchpadLink) { await persisted.softDelete(link.id); links = links.filter((item) => item.id !== link.id); menu = null; }
  async function saveEdit() { if (!editing) return; const input = parseLinkInput(editing.url, editing.title, editing.tags?.join(',') ?? '', editing.project_id, editing.description ?? '', editing.icon_color ?? 'auto'); const updated = await persisted.update({ ...editing, ...input }); links = links.map((item) => item.id === updated.id ? updated : item); editing = undefined; showToast('Link saved.'); }
  async function drop(target: number) { if (dragged < 0 || dragged === target) return; links = reorderLinks(links, dragged, target); dragged = -1; for (const [position, link] of links.entries()) await persisted.update({ ...link, position }); }
</script>

<div class="launchpad-view" aria-label="Launchpad">
  
  <div class="launchpad-toolbar"><form class="link-form" on:submit|preventDefault={addLink}><input aria-label="Link URL" bind:value={url} placeholder="https://example.com" /><input aria-label="Link title" bind:value={title} placeholder="Title" /><input aria-label="Link tags" bind:value={tags} placeholder="Tags" /><button type="submit">Add link</button></form>
  {#if error}<p class="error">{error}</p>{/if}
  <div class="tag-row"><div class="tag-filters"><button class:active={!selectedTag} on:click={() => selectedTag = ''}>All</button>{#each tagsList as tag}<button class:active={selectedTag === tag} on:click={() => selectedTag = tag}>#{tag}</button>{/each}</div><ScopeToggle scope={$launchpadScope} onChange={(value) => launchpadScope.set(value)} /></div></div>
  {#if createOpen}<div class="edit-overlay" on:click={(event) => event.target === event.currentTarget && (createOpen = false)}><form class="edit-modal" aria-label="New Launchpad Link" on:submit|preventDefault={addLink}><header><h4>New Link</h4><button type="button" aria-label="Close" on:click={() => createOpen = false}><img src="/tmp-icons/close-x.svg" alt="" /></button></header><input aria-label="Link URL" bind:value={url} placeholder="https://example.com" autofocus /><input aria-label="Link title" bind:value={title} placeholder="Title" /><input aria-label="Link tags" bind:value={tags} placeholder="Tags (comma separated)" /><footer><button type="button" on:click={() => createOpen = false}>Cancel</button><button type="submit">Add Link</button></footer></form></div>{/if}
  {#if pinnedLinks.length}<section class="link-section"><h5>Pinned</h5><div class="link-grid">{#each pinnedLinks as link (link.id)}{@render LinkCard(link)}{/each}</div></section>{/if}
  {#if otherLinks.length}<section class="link-section"><h5>Other links</h5><div class="link-grid">{#each otherLinks as link (link.id)}{@render LinkCard(link)}{/each}</div></section>{/if}
  {#if editing}<div class="edit-overlay" on:click={(event) => event.target === event.currentTarget && (editing = undefined)}><form class="edit-modal" on:submit|preventDefault={saveEdit}><header><h4>{editing.title}</h4><button type="button" aria-label="Close" on:click={() => editing = undefined}><img src="/tmp-icons/close-x.svg" alt="" /></button></header><input aria-label="Edit link URL" bind:value={editing.url} /><input aria-label="Custom icon URL" bind:value={editing.icon_url} placeholder="Custom icon URL (optional)" /><label>Icon background <input type="color" aria-label="Icon background color" value={editing.icon_color === 'auto' ? '#dbe4f0' : editing.icon_color ?? '#dbe4f0'} on:input={(event) => editing = { ...editing!, icon_color: (event.currentTarget as HTMLInputElement).value }} /></label><input aria-label="Edit link tags" value={editing.tags?.join(', ') ?? ''} on:input={(event) => editing = { ...editing!, tags: (event.currentTarget as HTMLInputElement).value.split(',').map((tag) => tag.trim()).filter(Boolean) }} placeholder="Tags (comma separated)" /><textarea aria-label="Edit link description" bind:value={editing.description} placeholder="Description (optional)"></textarea><footer><button type="button" on:click={() => editing = undefined}>Cancel</button><button type="submit">Save</button></footer></form></div>{/if}
</div>

{#snippet LinkCard(link: LaunchpadLink)}<article class:blurred={link.blurred} class="link-tile" draggable="true" on:dragstart={() => dragged = links.findIndex((item) => item.id === link.id)} on:dragover|preventDefault on:drop={() => drop(links.findIndex((item) => item.id === link.id))}><a href={link.url} target="_blank" rel="noreferrer"><span class="favicon" style={`background:${link.icon_color && link.icon_color !== 'auto' ? link.icon_color : 'var(--accent-secondary)'}`}><img src={faviconUrl(link.url)} alt="" /></span><span class="link-copy"><strong>{link.title}</strong><small>{link.url}</small></span></a><div class="card-actions"><button aria-label="Toggle link blur" on:click|stopPropagation={() => toggle(link, 'blurred')}><img src={`/tmp-icons/${link.blurred ? 'obfuscated' : 'obfuscation'}.svg`} alt="" /></button><button aria-label={link.pinned ? 'Unpin link' : 'Pin link'} on:click|stopPropagation={() => toggle(link, 'pinned')}><img src={`/tmp-icons/${link.pinned ? 'pin-filled' : 'pin'}.svg`} alt="" /></button><button aria-label="Link actions" on:click|stopPropagation={() => menu = menu === link.id ? null : link.id}><img src="/tmp-icons/overflow-ellipsis.svg" alt="" /></button>{#if menu === link.id}<div class="menu"><button on:click={() => { editing = { ...link }; menu = null; }}><img src="/tmp-icons/pencil.svg" alt="" /> Edit</button><button on:click={() => archive(link)}><img src="/tmp-icons/archive.svg" alt="" /> Archive</button><button on:click={() => remove(link)}><img src="/tmp-icons/trash.svg" alt="" /> Delete</button></div>{/if}</div></article>{/snippet}

<style>.launchpad-view{padding:.25rem 0}.launchpad-toolbar,.link-form,.tag-row,.link-tile a{display:flex;align-items:center}.launchpad-toolbar{justify-content:space-between;margin-bottom:1rem}.eyebrow{margin:0;color:var(--text-muted);font-size:.68rem;text-transform:uppercase}h4,h5{margin:.2rem 0}.link-section h5{margin:1.2rem 0 .7rem;font-size:1.1rem}input,textarea,button{padding:.6rem;border:1px solid var(--border-custom);border-radius:.4rem;background:var(--bg-elevated);color:var(--text-main)}button{cursor:pointer}.link-form{gap:.4rem}.link-form input{flex:1}.tag-row{gap:.3rem;margin:.8rem 0}.tag-row button{padding:.3rem .5rem}.tag-row button.active{background:var(--accent-secondary);border-color:var(--accent-primary);font-weight:700}.link-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:.75rem}.link-tile{position:relative;min-height:6.5rem;padding:.85rem;border:1px solid var(--border-custom);border-radius:.65rem;background:var(--bg-elevated)}.link-tile a{gap:.65rem;color:var(--text-main);text-decoration:none}.favicon{display:grid;place-items:center;width:2rem;height:2rem;flex:none;border-radius:.5rem}.favicon img{width:1.5rem;height:1.5rem}.link-copy{display:grid;min-width:0;gap:.2rem}.link-copy strong,.link-copy small{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.link-copy small{color:var(--text-muted);font-size:.7rem}.card-actions{position:absolute;right:.45rem;bottom:.4rem;display:flex;gap:.15rem;opacity:0}.link-tile:hover .card-actions,.card-actions:focus-within{opacity:1}.card-actions button{padding:.2rem .3rem;border:0;background:transparent}.card-actions img,.menu img,.edit-modal img{width:1rem;height:1rem;vertical-align:middle}.menu{position:absolute;right:0;bottom:2rem;z-index:4;display:grid;min-width:7rem;padding:.25rem;border:1px solid var(--border-custom);border-radius:.4rem;background:var(--bg-primary);box-shadow:0 .4rem 1rem rgb(0 0 0/.15)}.menu button{text-align:left;border:0}.blurred .link-copy{filter:blur(var(--blur-intensity))}.error{color:#c84d5d}.edit-overlay{position:fixed;z-index:30;inset:0;display:grid;place-items:center;background:rgb(0 0 0/.5)}.edit-modal{display:grid;gap:.8rem;width:min(42rem,calc(100vw - 2rem));padding:1.2rem;border:1px solid var(--border-custom);border-radius:.7rem;background:var(--bg-primary)}.edit-modal header,.edit-modal footer{display:flex;align-items:center;justify-content:space-between}.edit-modal header button{border:0;background:transparent}.edit-modal textarea{min-height:6rem}.edit-modal footer{justify-content:flex-end;gap:.4rem}@media(max-width:1100px){.link-grid{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:720px){.link-form{align-items:stretch;flex-direction:column}.link-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}</style>
