<script lang="ts">
  import { projects, selectedProjectId, createProject, renameProject, rekeyProject, archiveProjectById, restoreProjectById, deleteProjectById, selectProject } from '../projects/state';
  import { showToast } from '../ui/toast';
  let name = ''; let editingId: string | null = null; let editingName = ''; let editingProjectId = '';
  function add(): void { if (!name.trim()) { showToast('Project name is required.', 'error'); return; } try { createProject(name); name = ''; showToast('Project created.'); } catch (cause) { showToast(cause instanceof Error ? cause.message : 'Unable to create project.', 'error'); } }
  function beginEdit(id: string, current: string): void { editingId = id; editingProjectId = id; editingName = current; }
  function saveEdit(): void { if (editingId) { try { rekeyProject(editingId, editingProjectId); renameProject(editingProjectId, editingName); showToast('Project saved.'); } catch (cause) { showToast(cause instanceof Error ? cause.message : 'Unable to save project.', 'error'); } } editingId = null; }
</script>
<section class="projects-panel"><div class="project-heading"><div><h4>Projects</h4><p>Manage names, IDs, scope, archives, and deletion.</p></div></div><div class="project-create"><input aria-label="New project name" bind:value={name} placeholder="New project name" /><button on:click={add}>Create project</button></div><div class="project-list"><button class:active={!$selectedProjectId} on:click={() => selectProject(null)}>All projects</button>{#each $projects.filter((project) => project.deleted_at === null) as project}<div class="project-row">{#if editingId === project.id}<input aria-label="Edit project id" bind:value={editingProjectId} /><input aria-label="Edit project name" bind:value={editingName} /><button class="small" on:click={saveEdit}>Save</button>{:else}<button class:active={$selectedProjectId === project.id} on:click={() => selectProject(project.id)}>{project.name}</button><button class="small" on:click={() => beginEdit(project.id, project.name)}>Edit</button><button class="small" on:click={() => archiveProjectById(project.id)}>Archive</button>{/if}</div>{/each}</div>{#if $projects.some((project) => project.deleted_at !== null)}<details><summary>Archived</summary>{#each $projects.filter((project) => project.deleted_at !== null) as project}<div class="project-row"><span>{project.name}</span><button class="small" on:click={() => restoreProjectById(project.id)}>Unarchive</button><button class="small danger" on:click={() => deleteProjectById(project.id)}>Delete</button></div>{/each}</details>{/if}</section>
<style>.projects-panel { display: grid; gap: .8rem; } .project-heading, .project-create, .project-row { display: flex; align-items: center; gap: .5rem; } h4 { margin: 0; } p { margin: .25rem 0 0; color: var(--text-muted); font-size: .78rem; } input { min-width: 0; flex: 1; padding: .55rem; border: 1px solid var(--border-custom); border-radius: .4rem; background: var(--bg-elevated); color: var(--text-main); } button { padding: .5rem .65rem; border: 1px solid var(--border-custom); border-radius: .4rem; background: var(--bg-elevated); color: var(--text-main); cursor: pointer; } .project-list { display: grid; gap: .35rem; } .project-list > button, .project-row > button:first-child { flex: 1; text-align: left; } .small { padding: .35rem .5rem; font-size: .7rem; } .active { background: var(--accent-secondary); } .danger { color: #c84d5d; } details { color: var(--text-muted); font-size: .8rem; }</style>
