<script lang="ts">
  import { selectedProjectId, projects } from '../projects/state'; import { routinesScope } from '../projects/view-scopes'; import ScopeToggle from './ScopeToggle.svelte';
  import { activeTimeLog, pauseTimer, startTimer } from '../time/state';
  import { routineIsDue, routineLabel, type Routine, type RoutineFrequency } from '../routines/routines';
  import { hydrateJsonState, readJsonState, writeJsonState } from '../storage/json-state';
  let routines: Routine[] = []; let selected: Routine | undefined; let showArchived = false; let editing = false; let title = ''; let frequency: RoutineFrequency = 'daily'; let customWeekday = 1; let customOrdinal = 1;
  const key = 'dashboard.routines.v1';
  async function load(): Promise<void> { routines = await hydrateJsonState(key, readJsonState(key, [])); }
  function persist(): void { writeJsonState(key, routines); }
  void load();
  $: visible = routines.filter((routine) => !routine.archived === !showArchived && ($routinesScope === 'all' || !$selectedProjectId || routine.project_id === $selectedProjectId));
  function open(routine?: Routine): void { selected = routine ? { ...routine } : { id: '', project_id: $selectedProjectId ?? 'default', title: '', description: '', frequency: 'daily', interval: 1, weekdays: [], ordinals: [], blurred: false, archived: false, last_completed_at: null }; editing = true; title = routine?.title ?? ''; frequency = routine?.frequency ?? 'daily'; }
  function save(): void { if (!title.trim()) return; const routine: Routine = { id: selected?.id || crypto.randomUUID(), project_id: selected?.project_id ?? $selectedProjectId ?? 'default', title: title.trim(), description: selected?.description ?? '', frequency, interval: 1, weekdays: frequency === 'custom' ? [customWeekday] : [], ordinals: frequency === 'custom' ? [customOrdinal] : [], blurred: selected?.blurred ?? false, archived: selected?.archived ?? false, last_completed_at: selected?.last_completed_at ?? null }; routines = selected?.id ? routines.map((item) => item.id === routine.id ? routine : item) : [...routines, routine]; persist(); selected = routine; editing = false; }
  function complete(routine: Routine): void { routines = routines.map((item) => item.id === routine.id ? { ...item, last_completed_at: Date.now() } : item); persist(); }
  function toggleBlur(routine: Routine): void { routines = routines.map((item) => item.id === routine.id ? { ...item, blurred: !item.blurred } : item); persist(); }
  function archive(routine: Routine): void { routines = routines.map((item) => item.id === routine.id ? { ...item, archived: !item.archived } : item); persist(); selected = undefined; }
  function remove(routine: Routine): void { routines = routines.filter((item) => item.id !== routine.id); persist(); selected = undefined; }
</script>
<div class="focus-panel"><div class="panel-heading"><h2>Routines</h2><ScopeToggle scope={$routinesScope} onChange={(value) => routinesScope.set(value)} /></div><div class="routine-toolbar"><button on:click={() => showArchived = !showArchived}>{showArchived ? 'Hide Archived' : 'Show Archived'}</button><button aria-label="Create routine" on:click={() => open()}><img src="tmp-icons/add-plus.svg" alt="" /></button></div>{#if visible.length}{#each visible as routine}<article class:completed={!routineIsDue(routine)} class:blurred={routine.blurred} on:click={() => open(routine)}><input type="checkbox" checked={!routineIsDue(routine)} aria-label={`Complete ${routine.title}`} on:click|stopPropagation={() => complete(routine)} /><div class="routine-copy"><strong>{routine.title}</strong><small>{routineLabel(routine)}</small></div><div class="hover-actions"><button aria-label="Toggle blur" on:click|stopPropagation={() => toggleBlur(routine)}><img src={`tmp-icons/${routine.blurred ? 'obfuscated' : 'obfuscation'}.svg`} alt="" /></button>{#if $activeTimeLog?.title === routine.title && $activeTimeLog?.project_id === routine.project_id}<button aria-label="Pause routine timer" on:click|stopPropagation={pauseTimer}><img src="tmp-icons/pause.svg" alt="" /></button>{:else}<button aria-label="Start time log" on:click|stopPropagation={() => startTimer(routine.title, routine.description, routine.project_id)}><img src="tmp-icons/play.svg" alt="" /></button>{/if}<details on:click|stopPropagation><summary aria-label="Routine actions"><img src="tmp-icons/overflow-ellipsis.svg" alt="" /></summary><button on:click={() => open(routine)}><img src="tmp-icons/pencil.svg" alt="" /> Edit</button><button on:click={() => archive(routine)}><img src="tmp-icons/archive.svg" alt="" /> {routine.archived ? 'Unarchive' : 'Archive'}</button><button on:click={() => remove(routine)}><img src="tmp-icons/trash.svg" alt="" /> Delete</button></details></div></article>{/each}{:else}<div class="empty-state">No routines yet.</div>{/if}</div>
{#if selected}<div class="backdrop" role="presentation" on:click={(event) => event.target === event.currentTarget && (selected = undefined)}><section class="modal" role="dialog" aria-modal="true" on:click|stopPropagation><header><h3>{editing ? (selected.id ? 'Edit Routine' : 'New Routine') : selected.title}</h3><button class="close-x" aria-label="Close" on:click={() => selected = undefined}>×</button></header>{#if editing}<label>Title<input bind:value={title} aria-label="Routine title" /></label><label>Repeat<select bind:value={frequency}><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option><option value="custom">Custom ordinal weekday</option></select></label>{#if frequency === 'custom'}<label>Weekday<select bind:value={customWeekday}><option value="0">Sunday</option><option value="1">Monday</option><option value="2">Tuesday</option><option value="3">Wednesday</option><option value="4">Thursday</option><option value="5">Friday</option><option value="6">Saturday</option></select></label><label>Ordinal<select bind:value={customOrdinal}><option value="1">1st</option><option value="2">2nd</option><option value="3">3rd</option><option value="4">4th</option></select></label>{/if}<footer><button on:click={() => selected = undefined}>Cancel</button><button on:click={save}>Save</button></footer>{:else}<p>{routineLabel(selected)}</p><footer><button on:click={() => selected && startTimer(selected.title, selected.description, selected.project_id)}><img src="tmp-icons/circle-play.svg" alt="" /> Start</button><button on:click={() => toggleBlur(selected!)}><img src={`tmp-icons/${selected?.blurred ? 'obfuscated' : 'obfuscation'}.svg`} alt="" /> Blur</button><button on:click={() => editing = true}><img src="tmp-icons/pencil.svg" alt="" /> Edit</button><button on:click={() => archive(selected!)}><img src="tmp-icons/archive.svg" alt="" /> Archive</button><button on:click={() => remove(selected!)}><img src="tmp-icons/trash.svg" alt="" /> Delete</button></footer>{/if}</section></div>{/if}
<style>.focus-panel{display:grid;align-content:start;gap:.65rem;min-height:0;height:100%;overflow-y:auto;padding:1.15rem 1rem}.panel-heading,.routine-toolbar,article,.hover-actions,footer{display:flex;align-items:center}.panel-heading{justify-content:space-between}.panel-heading h2{margin:0}.panel-heading button,.routine-toolbar button,article button,summary,footer button{padding:.4rem .55rem;border:1px solid var(--border-custom);border-radius:.35rem;background:var(--bg-elevated);color:var(--text-main);cursor:pointer}.panel-heading button.active{background:var(--accent-secondary);font-weight:700}.routine-toolbar{justify-content:space-between}.routine-toolbar button[aria-label="Create routine"]{display:grid;place-items:center;width:2rem;height:2rem;padding:.35rem}.routine-toolbar button[aria-label="Create routine"] img{width:1rem;height:1rem;filter:none}:root[data-theme='dark'] .routine-toolbar button[aria-label="Create routine"] img{filter:invert(1)}article{position:relative;gap:.55rem;padding:.7rem;border:1px solid var(--border-custom);border-radius:.45rem;background:var(--bg-elevated);cursor:pointer}article.completed{opacity:.5}.routine-copy{display:grid;gap:.2rem;flex:1}.routine-copy small{color:var(--text-muted)}.hover-actions{opacity:0;gap:.2rem;margin-left:auto}.hover-actions details{position:relative}.hover-actions details[open]{position:relative}.hover-actions details button{position:absolute;right:0;z-index:4;min-width:8rem;margin-top:.2rem;background:var(--bg-primary)}.hover-actions img,summary img{width:1rem;height:1rem;vertical-align:middle}.hover-actions details{position:relative}.hover-actions details[open]{display:grid}.hover-actions details button{display:block;text-align:left}.hover-actions summary{list-style:none}.hover-actions summary::-webkit-details-marker{display:none}article:hover .hover-actions{opacity:1}.blurred .routine-copy{filter:blur(var(--blur-intensity))}.empty-state{padding:2rem;color:var(--text-muted)}.backdrop{position:fixed;inset:0;z-index:20;display:grid;place-items:center;background:rgb(0 0 0/.55)}.modal{display:grid;gap:1rem;width:min(32rem,calc(100vw - 2rem));padding:1.2rem;border:1px solid var(--border-custom);border-radius:.7rem;background:var(--bg-primary);color:var(--text-main)}.modal header{display:flex;align-items:center;justify-content:space-between}.modal .close-x{padding:0;border:0;background:transparent;color:var(--text-main);font-size:1.6rem;line-height:1}.modal label{display:grid;gap:.3rem;color:var(--text-muted)}.modal input,.modal select{padding:.6rem;border:1px solid var(--border-custom);border-radius:.35rem;background:var(--bg-elevated);color:var(--text-main)}footer{justify-content:flex-end;gap:.4rem}</style>
