<script lang="ts">
  import { onMount } from 'svelte'; import { PersistentCollection } from '../storage/persistent'; import { selectedProjectId } from '../projects/state'; import { searchScope } from '../projects/view-scopes'; import ScopeToggle from './ScopeToggle.svelte'; import type { StoreName } from '../storage/models'; import { navigateTo } from '../ui/navigation'; import { openDocument, loadDocuments } from '../documents/state'; import { requestCalendarOpen } from '../calendar/open'; import { requestTimeLogOpen } from '../time/open';
  type Result = { type: string; title: string; text: string; value: any };
  const stores: Array<[StoreName, string, (value: any) => { title: string; text: string }]> = [['tasks','Task',(value)=>({title:value.title,text:value.notes??''})],['events','Event',(value)=>({title:value.title,text:`${value.description??''} ${value.location??''}`})],['notes','Note',(value)=>({title:value.title,text:value.content??''})],['documents','Doc',(value)=>({title:value.title,text:value.content??''})],['launchpad_links','Launchpad link',(value)=>({title:value.title,text:`${value.url} ${(value.tags??[]).join(' ')}`})],['time_logs','Time log',(value)=>({title:value.title,text:value.description??''})]];
  let query = ''; let records: Result[] = [];
  onMount(async () => { await loadDocuments(); records = (await Promise.all(stores.map(async ([store, type, map]) => { try { return (await new PersistentCollection(store).load()).map((value) => ({ type, value, ...map(value) })); } catch { return []; } }))).flat(); });
  $: scopedRecords = records.filter((record) => $searchScope === 'all' || !$selectedProjectId || record.value.project_id === $selectedProjectId);
  $: results = scopedRecords.filter((record) => `${record.title} ${record.text}`.toLowerCase().includes(query.trim().toLowerCase()));
  function openResult(result: Result): void { if (result.type === 'Task' || result.type === 'Event') { navigateTo('calendar'); requestCalendarOpen(result.value); return; } if (result.type === 'Time log') { navigateTo('time-logs'); requestTimeLogOpen(result.value); return; } if (result.type === 'Doc' || result.type === 'Note') { navigateTo('documents'); openDocument({ ...result.value, tags: result.value.tags ?? [], archived: result.value.archived ?? false }); return; } if (result.type === 'Launchpad link') window.open(result.value.url, '_blank', 'noopener,noreferrer'); }
</script>
<div class="focus-panel p-4" aria-label="Search sidebar"><div class="panel-heading"><h2>Search</h2><ScopeToggle scope={$searchScope} onChange={(value) => searchScope.set(value)} /></div><p>Find notes, tasks, events, and launchpad links in one list.</p><input class="search-field" aria-label="Search all data" bind:value={query} placeholder="Search everything…" />{#if query.trim()}<div class="results" aria-label="Search results">{#if results.length}{#each results as result}<article><span>{result.type}</span><strong>{result.title}</strong>{#if result.text}<small>{result.text}</small>{/if}<button class="open-result" on:click={() => openResult(result)}>Open</button></article>{/each}{:else}<div class="result-placeholder">No matching results</div>{/if}</div>{:else}<div class="result-placeholder idle">Search across all data types</div>{/if}</div>
<style>.focus-panel{display:grid;grid-template-rows:auto auto auto minmax(0,1fr);gap:.8rem;height:100%;min-height:0;box-sizing:border-box;overflow-y:scroll;background:var(--bg-primary)}.p-4{padding:1rem}.panel-heading{display:flex;align-items:center;justify-content:space-between;gap:.5rem}h2{margin:0;font-size:1.35rem}.panel-heading button{padding:.55rem .75rem;border:1px solid var(--border-custom);border-radius:.4rem;background:var(--bg-elevated);color:var(--text-main);font-size:.75rem}p{max-width:22rem;margin:0;color:var(--text-muted);font-size:.85rem;line-height:1.45}.search-field{width:100%;box-sizing:border-box;padding:.8rem;border:2px solid var(--border-custom);border-radius:.5rem;background:var(--bg-elevated);color:var(--text-main);font-size:1rem;outline-color:var(--accent-primary)}.results{display:grid;align-content:start;gap:.65rem;min-height:0;overflow-y:auto}.results article{position:relative;display:grid;gap:.35rem;padding:.8rem;border:1px solid var(--border-custom);border-radius:.6rem;background:var(--bg-elevated)}.results span{width:max-content;padding:.25rem .5rem;border-radius:1rem;background:var(--accent-secondary);color:var(--text-muted);font-size:.65rem;text-transform:uppercase;letter-spacing:.06em}.results strong{padding-right:3rem;font-size:.95rem}.results small{overflow:hidden;color:var(--text-muted);font-size:.8rem;line-height:1.35;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical}.open-result{position:absolute;right:.8rem;top:3rem;border:0;background:transparent;color:var(--text-muted);font-size:.7rem;text-transform:uppercase}.open-result:hover{cursor:pointer;text-decoration:underline}.result-placeholder{display:grid;place-items:center;min-height:8rem;padding:1rem;border:1px dashed var(--border-custom);border-radius:.6rem;color:var(--text-muted);text-align:center}.result-placeholder.idle{min-height:14rem}@media(max-width:720px){.panel-heading{align-items:flex-start;flex-direction:column}.panel-heading button{align-self:flex-end}}
</style>
