<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  import { taskFromDraft, type CalendarTask } from '../calendar/tasks';
  export let task: CalendarTask | undefined; export let date = new Date(); export let projectId = 'default'; export let mode: 'create' | 'detail' | 'edit' = 'create';
  const dispatch = createEventDispatcher<{ save: CalendarTask; delete: CalendarTask; start: CalendarTask; close: void }>(); let title = ''; let description = ''; let dueAt = ''; let blurred = false; let error = '';
  $: if (task && mode !== 'create' && !title) { title = task.title; description = task.description ?? ''; dueAt = inputDate(task.due_at); blurred = task.blurred ?? false; }
  $: if (mode === 'create' && !dueAt) dueAt = inputDate(date);
  function inputDate(value: Date | number): string { const d = new Date(value); const pad = (n: number) => String(n).padStart(2, '0'); return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`; }
  function save(): void { try { const next = taskFromDraft({ title, description, due_at: dueAt, project_id: projectId, blurred }, task?.id); dispatch('save', { ...next, completed: task?.completed ?? false }); } catch (cause) { error = cause instanceof Error ? cause.message : 'Unable to save task'; } }
  function close(): void { dispatch('close'); }
</script>
<div class="backdrop" role="presentation" on:click={(event) => event.target === event.currentTarget && close()}><section class="modal" role="dialog" aria-modal="true" aria-label="Task"><header><h3>{mode === 'create' ? 'Add Task' : mode === 'edit' ? 'Edit Task' : task?.title}</h3><button aria-label="Close" on:click={close}>×</button></header>{#if mode === 'detail' && task}<div class="details"><strong class:blurred={task.blurred}>{task.title}</strong><p>{task.description}</p><p>Due {new Date(task.due_at).toLocaleString()}</p><footer><button class="secondary" on:click={close}>Close</button><button on:click={() => dispatch('start', task)}>Play</button><button on:click={() => mode = 'edit'}>Edit</button><button class="danger" on:click={() => dispatch('delete', task)}>Delete</button></footer></div>{:else}<form on:submit|preventDefault={save}><label>Title *<input aria-label="Task title" bind:value={title} autofocus /></label><label>Description<textarea aria-label="Task description" bind:value={description}></textarea></label><label>Due date<input type="datetime-local" aria-label="Task due date" bind:value={dueAt} /></label><label class="check"><input type="checkbox" bind:checked={blurred} /> Blur task on screen</label>{#if error}<p class="error">{error}</p>{/if}<footer><button type="button" class="secondary" on:click={close}>Cancel</button><button type="submit">{mode === 'edit' ? 'Save changes' : 'Add Task'}</button></footer></form>{/if}</section></div>
<style>.backdrop { position: fixed; z-index: 30; inset: 0; display: grid; place-items: center; background: rgb(0 0 0 / .55); } .modal { width: min(42rem, calc(100vw - 2rem)); border: 1px solid var(--border-custom); border-radius: .7rem; background: var(--bg-primary); color: var(--text-main); } header, footer { display: flex; align-items: center; justify-content: space-between; gap: .45rem; } header { padding: 1rem 1.2rem; border-bottom: 1px solid var(--border-custom); } header button { border: 0; background: transparent; color: inherit; font-size: 1.4rem; } h3 { margin: 0; } form, .details { display: grid; gap: .9rem; padding: 1.2rem; } label { display: grid; gap: .35rem; color: var(--text-muted); font-size: .8rem; } input, textarea { width: 100%; padding: .6rem; border: 1px solid var(--border-custom); border-radius: .35rem; background: var(--bg-elevated); color: var(--text-main); } textarea { min-height: 4rem; } .check { display: flex; align-items: center; gap: .4rem; } .check input { width: auto; } footer { justify-content: flex-end; padding-top: .7rem; border-top: 1px solid var(--border-custom); } footer button { padding: .55rem .7rem; border: 1px solid var(--border-custom); border-radius: .35rem; background: var(--accent-primary); color: var(--text-inverse); cursor: pointer; } .secondary { background: var(--bg-secondary); color: var(--text-main); } .danger { background: #9b3544; } .details p { margin: 0; color: var(--text-muted); } .blurred { filter: blur(var(--blur-intensity)); } .error { color: #c84d5d; }</style>
