<script lang="ts">
  import { createEventDispatcher } from 'svelte'; import { taskFromDraft, type CalendarTask } from '../calendar/tasks'; import { projects } from '../projects/state'; import { startTimer } from '../time/state';
  export let task: CalendarTask | undefined; export let date = new Date(); export let projectId = 'default'; export let mode: 'create' | 'detail' | 'edit' = 'create';
  const dispatch = createEventDispatcher<{ save: CalendarTask; delete: CalendarTask; start: CalendarTask; close: void }>(); let title = ''; let description = ''; let dueAt = ''; let priority: 'low' | 'normal' | 'high' = 'normal'; let selectedProjectId = projectId; let blurred = false; let error = '';
  function play(): void { if (task) { startTimer(task.title, task.description ?? '', task.project_id, task.id); dispatch('start', task); } }
  $: if (task && mode !== 'create' && !title) { title = task.title; description = task.description ?? ''; dueAt = inputDate(task.due_at); priority = task.priority ?? 'normal'; selectedProjectId = task.project_id; blurred = task.blurred ?? false; }
  $: if (mode === 'create' && !dueAt) dueAt = inputDate(date);
  function inputDate(value: Date | number): string { const d = new Date(value); const pad = (n: number) => String(n).padStart(2, '0'); return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`; }
  function save(): void { try { const next = taskFromDraft({ title, description, due_at: dueAt, project_id: selectedProjectId, priority, blurred }, task?.id); dispatch('save', { ...next, completed: task?.completed ?? false }); } catch (cause) { error = cause instanceof Error ? cause.message : 'Unable to save task'; } }
  function close(): void { dispatch('close'); }
</script>
<div class="backdrop" role="presentation" on:click={(event) => event.target === event.currentTarget && close()}><section class="modal" role="dialog" aria-modal="true" aria-label="Task"><header><h3>{mode === 'create' ? 'Add Task' : mode === 'edit' ? 'Edit Task' : task?.title}</h3><button aria-label="Close" on:click={close}>×</button></header>{#if mode === 'detail' && task}<div class="details"><strong class="detail-title">{task.title}</strong><p>{task.description}</p><p><strong>Project</strong><br />{$projects.find((item) => item.id === task.project_id)?.name ?? task.project_id}</p><p>Due {new Date(task.due_at).toLocaleString()}</p><footer><button class="secondary" on:click={close}>Close</button><button on:click={play}>Play</button><button on:click={() => mode = 'edit'}>Edit</button><button class="danger" on:click={() => dispatch('delete', task)}>Delete</button></footer></div>{:else}<form on:submit|preventDefault={save}><label>Title *<input aria-label="Task title" bind:value={title} autofocus /></label><label>Description<textarea aria-label="Task description" bind:value={description}></textarea></label><div class="two-col"><label>Due Date<input type="datetime-local" aria-label="Task due date" bind:value={dueAt} /></label><label>Priority<select aria-label="Task priority" bind:value={priority}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option></select></label></div><label>Project<select aria-label="Task project" bind:value={selectedProjectId}>{#each $projects.filter((item) => !item.deleted_at) as project}<option value={project.id}>{project.name}</option>{/each}<option value="default">Default project</option></select><small>Choose which project this task belongs to.</small></label>{#if error}<p class="error">{error}</p>{/if}<footer><button type="button" class="secondary" on:click={close}>Cancel</button><button type="submit">{mode === 'edit' ? 'Save Changes' : 'Add Task'}</button></footer></form>{/if}</section></div>
<style>
  .backdrop{position:fixed!important;z-index:1000;inset:0;display:grid;place-items:center;overflow:auto;padding:1rem;background:rgb(18 24 38/.58)}.modal{width:min(42rem,100%);max-height:calc(100vh - 2rem);overflow:auto;margin:auto;border:1px solid var(--border-custom);border-radius:.7rem;background:var(--bg-primary);color:var(--text-main);box-shadow:0 1.5rem 4rem rgb(0 0 0/.25)}header{display:flex;align-items:center;justify-content:space-between;padding:1.2rem 1.5rem;border-bottom:1px solid var(--border-custom)}h3{margin:0;font-size:1.35rem}header button{border:0;background:transparent;color:inherit;font-size:1.6rem}form,.details{display:grid;gap:1rem;padding:1.5rem}label{display:grid;gap:.35rem;color:var(--text-muted);font-size:.8rem}input,textarea,select{width:100%;padding:.65rem .7rem;border:1px solid var(--border-custom);border-radius:.35rem;background:var(--bg-elevated);color:var(--text-main);font:inherit}textarea{min-height:5rem;resize:vertical}small{color:var(--text-muted)}.two-col{display:grid;grid-template-columns:1fr 1fr;gap:.8rem}footer{display:flex;justify-content:flex-end;gap:.5rem;padding-top:.8rem;border-top:1px solid var(--border-custom)}footer button{padding:.6rem .8rem;border:1px solid var(--border-custom);border-radius:.4rem;background:var(--accent-primary);color:var(--text-inverse);cursor:pointer}.secondary{background:var(--bg-secondary);color:var(--text-main)}.danger{background:#9b3544}.details p{margin:0;color:var(--text-muted)}.detail-title{font:700 1.2rem 'Grenze Gotisch',serif;color:var(--text-main)}.error{color:#c84d5d}@media(max-width:600px){.two-col{grid-template-columns:1fr}}
</style>
