import { derived, get, writable } from 'svelte/store';
import { selectedProjectId } from '../projects/state';

export interface TimeLogEntry { id:string; group_id:string; project_id:string; title:string; description:string; location?:string; startInput?:string; endInput?:string; started_at:number; ended_at:number|null; duration_seconds:number; active:boolean; paused:boolean; blurred:boolean; }
const KEY='dashboard.time-logs.v1'; const read=():TimeLogEntry[]=>{try{return JSON.parse(localStorage.getItem(KEY)??'[]') as TimeLogEntry[]}catch{return[]}}; const write=(items:TimeLogEntry[])=>localStorage.setItem(KEY,JSON.stringify(items));
export const timeLogs=writable<TimeLogEntry[]>(read()); export const activeTimeLog=derived(timeLogs,($logs)=>{const active=$logs.find((log)=>log.active);if(!active)return undefined;return {...active,duration_seconds:$logs.filter((log)=>log.group_id===active.group_id).reduce((sum,log)=>sum+log.duration_seconds,0)}}); export const timerSetup=writable(false);
let interval:ReturnType<typeof setInterval>|undefined;
function refresh(){timeLogs.update((logs)=>logs.map((log)=>log.active?{...log,duration_seconds:Math.max(0,Math.floor((Date.now()-log.started_at)/1000))}:log));}
export function openTimerSetup(){timerSetup.set(true)} export function cancelTimerSetup(){timerSetup.set(false)}
export function startTimer(title:string,description:string,projectId?:string,groupId?:string){const now=Date.now();const id=crypto.randomUUID();const log:TimeLogEntry={id,group_id:groupId??id,project_id:projectId??get(selectedProjectId)??'default',title:title.trim()||'Untitled time entry',description:description.trim(),started_at:now,ended_at:null,duration_seconds:0,active:true,paused:false,blurred:false};const next=read().map((item)=>item.active?{...item,active:false,paused:true,ended_at:now}:item);write([...next,log]);timeLogs.set([...next,log]);timerSetup.set(false);if(interval)clearInterval(interval);interval=setInterval(refresh,1000);return log;}
export function logFromCalendarEvent(event:{id:string;project_id:string;title:string;description?:string;starts_at:number;ends_at:number}):TimeLogEntry{const log:TimeLogEntry={id:crypto.randomUUID(),group_id:event.id,project_id:event.project_id,title:event.title,description:event.description??'',started_at:event.starts_at,ended_at:event.ends_at,duration_seconds:Math.max(0,Math.floor((event.ends_at-event.starts_at)/1000)),active:false,paused:false,blurred:false};const next=[...read(),log];write(next);timeLogs.set(next);return log}
export function pauseTimer(){const now=Date.now();const current=get(activeTimeLog);if(!current)return;const saved={...current,active:false,paused:true,ended_at:now,duration_seconds:Math.floor((now-current.started_at)/1000)};update(saved);if(interval)clearInterval(interval);interval=undefined}
export function stopTimer(){const current=get(activeTimeLog);if(!current)return;const now=Date.now();update({...current,active:false,paused:false,ended_at:now,duration_seconds:Math.floor((now-current.started_at)/1000)});if(interval)clearInterval(interval);interval=undefined}
export function resumeTimer(log:TimeLogEntry){startTimer(log.title,log.description,log.project_id,log.group_id)}
export function update(log:TimeLogEntry){const next=get(timeLogs).map((item)=>item.id===log.id?log:item);write(next);timeLogs.set(next)}
export function deleteTimeLog(id:string){const next=get(timeLogs).filter((item)=>item.id!==id);write(next);timeLogs.set(next)}
export function toggleBlur(id:string){const log=get(timeLogs).find((item)=>item.id===id);if(log){const blurred=!log.blurred;const next=get(timeLogs).map((item)=>item.group_id===log.group_id?{...item,blurred}:item);write(next);timeLogs.set(next)}}
export const groupedTimeLogs=derived(timeLogs,($logs)=>{const groups=new Map<string,TimeLogEntry[]>();for(const log of $logs){const list=groups.get(log.group_id)??[];list.push(log);groups.set(log.group_id,list)}return [...groups.values()].map((entries)=>({parent:entries[0],entries,total_seconds:entries.reduce((total,entry)=>total+entry.duration_seconds,0)})).sort((a,b)=>b.parent.started_at-a.parent.started_at)});
export function formatTime(seconds:number){const safe=Math.max(0,Math.floor(seconds));return `${String(Math.floor(safe/3600)).padStart(2,'0')}:${String(Math.floor(safe%3600/60)).padStart(2,'0')}:${String(safe%60).padStart(2,'0')}`}
